# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.models.hc_rgb_image import HcRgbImage

class TestHcRgbImage(unittest.TestCase):
    """HcRgbImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HcRgbImage:
        """Test HcRgbImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HcRgbImage`
        """
        model = HcRgbImage()
        if include_optional:
            return HcRgbImage(
                device_id = 56,
                device_pid = '',
                experiment_id = 56,
                measure_angle = 56,
                measure_id = 56,
                rgb_image_path = '',
                round_id = 56,
                tray_barcode = '',
                tray_id = 56
            )
        else:
            return HcRgbImage(
        )
        """

    def testHcRgbImage(self):
        """Test HcRgbImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
