# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.action_api import ActionApi


class TestActionApi(unittest.TestCase):
    """ActionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionApi()

    def tearDown(self) -> None:
        pass

    def test_action(self) -> None:
        """Test case for action

        Returns one scheduled action by action ID.
        """
        pass

    def test_action_experiment(self) -> None:
        """Test case for action_experiment

        Returns all scheduled actions in the experiment defined by ID.
        """
        pass

    def test_action_group(self) -> None:
        """Test case for action_group

        Returns one group of scheduled actions by action group ID.
        """
        pass

    def test_action_group_round(self) -> None:
        """Test case for action_group_round

        Returns one group of scheduled actions to which a round defined by ID belongs.
        """
        pass

    def test_action_not_done_experiment(self) -> None:
        """Test case for action_not_done_experiment

        Returns all unfinished scheduled actions (with pending and running action state) in the experiment defined by ID.
        """
        pass

    def test_action_protocol(self) -> None:
        """Test case for action_protocol

        Returns one protocol of scheduled action by protocol ID.
        """
        pass

    def test_action_protocol_round(self) -> None:
        """Test case for action_protocol_round

        Returns one group of scheduled actions that belong to round defined by ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
