# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.scan3d_api import Scan3dApi


class TestScan3dApi(unittest.TestCase):
    """Scan3dApi unit test stubs"""

    def setUp(self) -> None:
        self.api = Scan3dApi()

    def tearDown(self) -> None:
        pass

    def test_scan3d(self) -> None:
        """Test case for scan3d

        Returns 3D imaging data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_scan3d_analysed_model_analyse(self) -> None:
        """Test case for scan3d_analysed_model_analyse

        Returns the analyzed 3D data as a triangulated 3D model defined by analyse ID.
        """
        pass

    def test_scan3d_analyzed_model(self) -> None:
        """Test case for scan3d_analyzed_model

        Returns the analyzed 3D data as a triangulated 3D model defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_scan3d_analyzed_model_measure(self) -> None:
        """Test case for scan3d_analyzed_model_measure

        Returns the analyzed 3D data as a triangulated 3D model defined by scan 3D measure ID.
        """
        pass

    def test_scan3d_imaging_extended_data(self) -> None:
        """Test case for scan3d_imaging_extended_data

        Returns 3D extended data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_scan3d_imaging_extended_data_measure(self) -> None:
        """Test case for scan3d_imaging_extended_data_measure

        Returns 3D imaging extended data by scan 3D measure ID.
        """
        pass

    def test_scan3d_imaging_measure(self) -> None:
        """Test case for scan3d_imaging_measure

        Returns 3D imaging data by scan 3D measure ID.
        """
        pass

    def test_scan3d_leaf_param(self) -> None:
        """Test case for scan3d_leaf_param

        Returns the 3D local leaf parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_scan3d_leaf_param_analyse(self) -> None:
        """Test case for scan3d_leaf_param_analyse

        Returns the 3D local leaf parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.
        """
        pass

    def test_scan3d_param(self) -> None:
        """Test case for scan3d_param

        Returns one 3D parameter by parameter ID.
        """
        pass

    def test_scan3d_param_used(self) -> None:
        """Test case for scan3d_param_used

        Returns the 3D plant and leaf parameters used in the analysis by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_scan3d_param_used_analyse(self) -> None:
        """Test case for scan3d_param_used_analyse

        Returns the 3D plant and leaf parameters used in the analysis defined by analyse ID.
        """
        pass

    def test_scan3d_plant_param(self) -> None:
        """Test case for scan3d_plant_param

        Returns the 3D plant parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_scan3d_plant_param_analyse(self) -> None:
        """Test case for scan3d_plant_param_analyse

        Returns the 3D plant parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
