# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_profile(self) -> None:
        """Test case for profile

        Returns one system profile by profile ID.
        """
        pass

    def test_profile_active(self) -> None:
        """Test case for profile_active

        Returns the active system profile.
        """
        pass

    def test_profile_id(self) -> None:
        """Test case for profile_id

        Returns a list of all system profile IDs in the database
        """
        pass


if __name__ == '__main__':
    unittest.main()
