# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.tray_api import TrayApi


class TestTrayApi(unittest.TestCase):
    """TrayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrayApi()

    def tearDown(self) -> None:
        pass

    def test_scales_mapping_tray(self) -> None:
        """Test case for scales_mapping_tray

        Returns a scales mapping for tray defined by ID.
        """
        pass

    def test_tray(self) -> None:
        """Test case for tray

        Returns one tray by tray ID.
        """
        pass

    def test_tray_profile(self) -> None:
        """Test case for tray_profile

        Returns one tray profile by tray profile ID.
        """
        pass

    def test_tray_profile_to_date_tray(self) -> None:
        """Test case for tray_profile_to_date_tray

        Returns one tray profile to which tray defined by ID was assigned on the defined time.
        """
        pass

    def test_tray_profile_tray(self) -> None:
        """Test case for tray_profile_tray

        Returns one tray profile to which tray defined by ID is assigned.
        """
        pass

    def test_tray_profile_used_tray(self) -> None:
        """Test case for tray_profile_used_tray

        Returns tray profiles to which tray defined by ID was assigned between defined times. Times is entered as the start and end time of the required interval. All tray profiles assigned to tray between these times will be returned.
        """
        pass

    def test_tray_round(self) -> None:
        """Test case for tray_round

        Returns all trays measured in the round defined by ID.
        """
        pass

    def test_tray_type(self) -> None:
        """Test case for tray_type

        Returns one tray type by tray type ID.
        """
        pass

    def test_tray_type_tray(self) -> None:
        """Test case for tray_type_tray

        Returns one tray type which is assigned to the tray defined by ID.
        """
        pass

    def test_tray_type_tray_profile(self) -> None:
        """Test case for tray_type_tray_profile

        Returns one tray type which is assigned to the tray profile defined by ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
