# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.system_log_api import SystemLogApi


class TestSystemLogApi(unittest.TestCase):
    """SystemLogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemLogApi()

    def tearDown(self) -> None:
        pass

    def test_system_log_date_log_tag(self) -> None:
        """Test case for system_log_date_log_tag

        Returns important events as system logs by log tag between defined times. Times is entered as the start and end time of the required interval.
        """
        pass

    def test_system_log_date_log_type(self) -> None:
        """Test case for system_log_date_log_type

        Returns important events as system logs by log type between defined times. Times is entered as the start and end time of the required interval.
        """
        pass

    def test_system_log_date_round(self) -> None:
        """Test case for system_log_date_round

        Returns important events as system logs by round ID between defined times. Times is entered as the start and end time of the required interval. System logs are only optionally assigned to the round.
        """
        pass

    def test_system_log_date_tray(self) -> None:
        """Test case for system_log_date_tray

        Returns important events as system logs by tray ID between defined times. Times is entered as the start and end time of the required interval. System logs are only optionally assigned to the tray.
        """
        pass

    def test_system_log_log_tag(self) -> None:
        """Test case for system_log_log_tag

        Returns a list of all used system log tag.
        """
        pass

    def test_system_log_log_type(self) -> None:
        """Test case for system_log_log_type

        Returns a list of all used system log types.
        """
        pass

    def test_system_log_round(self) -> None:
        """Test case for system_log_round

        Returns important events as system logs by round ID. System logs are only optionally assigned to the round.
        """
        pass

    def test_system_log_tray(self) -> None:
        """Test case for system_log_tray

        Returns important events as system logs by tray ID. System logs are only optionally assigned to the tray.
        """
        pass


if __name__ == '__main__':
    unittest.main()
