# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.msc_api import MscApi


class TestMscApi(unittest.TestCase):
    """MscApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MscApi()

    def tearDown(self) -> None:
        pass

    def test_msc_calibration(self) -> None:
        """Test case for msc_calibration

        Returns one Multispectral calibration for individual groups of lights with information about the exposure and gain of the camera defined by calibration ID.
        """
        pass

    def test_msc_calibration_light(self) -> None:
        """Test case for msc_calibration_light

        Returns a list of all lightsettings if no ID is passed. Or the light output setting for light group calibration defined by calibration light ID.
        """
        pass

    def test_msc_calibration_light_set(self) -> None:
        """Test case for msc_calibration_light_set

        Returns the Multispectral calibration for individual groups of lights with information about the exposure and gain of the camera defined by light set ID.
        """
        pass

    def test_msc_imaging(self) -> None:
        """Test case for msc_imaging

        Returns Multispectral imaging data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_msc_imaging_extended_data(self) -> None:
        """Test case for msc_imaging_extended_data

        Returns Multispectral extended data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_msc_imaging_extended_data_measure(self) -> None:
        """Test case for msc_imaging_extended_data_measure

        Returns Multispectral imaging extended data by MSC measure ID.
        """
        pass

    def test_msc_imaging_measure(self) -> None:
        """Test case for msc_imaging_measure

        Returns Multispectral imaging data by MSC measure ID.
        """
        pass

    def test_msc_leaf_param(self) -> None:
        """Test case for msc_leaf_param

        Returns the Multispectral Statistic leaf parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_msc_leaf_param_analyse(self) -> None:
        """Test case for msc_leaf_param_analyse

        Returns the Multispectral statistic leaf parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.
        """
        pass

    def test_msc_light_set(self) -> None:
        """Test case for msc_light_set

        Returns one set of the lights for multispectral camera service defined by light set ID.
        """
        pass

    def test_msc_light_set_used(self) -> None:
        """Test case for msc_light_set_used

        Returns the sets of the lights for multispectral camera service used in the measure for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass

    def test_msc_param(self) -> None:
        """Test case for msc_param

        Returns one Multispectral parameter by parameter ID.
        """
        pass

    def test_msc_param_image(self) -> None:
        """Test case for msc_param_image

        Returns the Multispectral parameter images for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_msc_param_image_analyse(self) -> None:
        """Test case for msc_param_image_analyse

        Returns the Multispectral parameter image for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.
        """
        pass

    def test_msc_param_used(self) -> None:
        """Test case for msc_param_used

        Returns the Multispectral plant and leaf parameters used in the analysis by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_msc_param_used_analyse(self) -> None:
        """Test case for msc_param_used_analyse

        Returns Multispectral used plant parameters by analyse ID.
        """
        pass

    def test_msc_plant_mask(self) -> None:
        """Test case for msc_plant_mask

        Returns Multispectral plant mask by device, round and tray ID.
        """
        pass

    def test_msc_plant_mask_measure(self) -> None:
        """Test case for msc_plant_mask_measure

        Returns the Multispectral plant mask created for the measured tray defined by MSC measure ID.
        """
        pass

    def test_msc_plant_param(self) -> None:
        """Test case for msc_plant_param

        Returns the Multispectral statistic plant parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.
        """
        pass

    def test_msc_plant_param_analyse(self) -> None:
        """Test case for msc_plant_param_analyse

        Returns the Multispectral plant parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
