# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plantscreen.api.spray_api import SprayApi


class TestSprayApi(unittest.TestCase):
    """SprayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SprayApi()

    def tearDown(self) -> None:
        pass

    def test_spray_action(self) -> None:
        """Test case for spray_action

        Return spray action data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
