site_name: Documentation-Test
site_description: python documentation test

theme: readthedocs
repo_name: wurDevTim/Documentation-Test
repo_url: https://github.com/wurDevTim/Documentation-Test

nav:
  - CHANGELOG: CHANGELOG.md
  - index: index.md
  - Code:
    - admin_api: Code/admin_api.md
    - complete_api: Code/complete_api.md
    - imaging_api: Code/imaging_api.md
    - swagger_file: Code/swagger_file.md
    - system_api: Code/system_api.md
    - Models:
      - experiment_models: Code/Models/experiment_models.md
      - profile_models: Code/Models/profile_models.md
      - spectrum_device_models: Code/Models/spectrum_device_models.md
    - Swagger_docs:
      - Action: Code/Swagger_docs/Action.md
      - ActionApi: Code/Swagger_docs/ActionApi.md
      - ActionGroup: Code/Swagger_docs/ActionGroup.md
      - ActionProtocol: Code/Swagger_docs/ActionProtocol.md
      - BufferApi: Code/Swagger_docs/BufferApi.md
      - BufferHistory: Code/Swagger_docs/BufferHistory.md
      - Device: Code/Swagger_docs/Device.md
      - DeviceApi: Code/Swagger_docs/DeviceApi.md
      - Experiment: Code/Swagger_docs/Experiment.md
      - ExperimentApi: Code/Swagger_docs/ExperimentApi.md
      - ExperimentIDWrapper: Code/Swagger_docs/ExperimentIDWrapper.md
      - ExperimentNote: Code/Swagger_docs/ExperimentNote.md
      - FcApi: Code/Swagger_docs/FcApi.md
      - FcImaging: Code/Swagger_docs/FcImaging.md
      - FileApi: Code/Swagger_docs/FileApi.md
      - HcApi: Code/Swagger_docs/HcApi.md
      - HcImaging: Code/Swagger_docs/HcImaging.md
      - HcRgbImage: Code/Swagger_docs/HcRgbImage.md
      - Imaging: Code/Swagger_docs/Imaging.md
      - InlineResponse200: Code/Swagger_docs/InlineResponse200.md
      - InlineResponse2001: Code/Swagger_docs/InlineResponse2001.md
      - IrApi: Code/Swagger_docs/IrApi.md
      - JsonActionByExperimentIDNotDoneResult: Code/Swagger_docs/JsonActionByExperimentIDNotDoneResult.md
      - JsonActionByExperimentIDResult: Code/Swagger_docs/JsonActionByExperimentIDResult.md
      - JsonActionGroupByRoundIDResult: Code/Swagger_docs/JsonActionGroupByRoundIDResult.md
      - JsonActionGroupResult: Code/Swagger_docs/JsonActionGroupResult.md
      - JsonActionProtocolByRoundIDResult: Code/Swagger_docs/JsonActionProtocolByRoundIDResult.md
      - JsonActionProtocolResult: Code/Swagger_docs/JsonActionProtocolResult.md
      - JsonActionResult: Code/Swagger_docs/JsonActionResult.md
      - JsonBufferHistoryByDateResult: Code/Swagger_docs/JsonBufferHistoryByDateResult.md
      - JsonBufferHistoryResult: Code/Swagger_docs/JsonBufferHistoryResult.md
      - JsonDeviceActiveResult: Code/Swagger_docs/JsonDeviceActiveResult.md
      - JsonDeviceByProfileIDResult: Code/Swagger_docs/JsonDeviceByProfileIDResult.md
      - JsonDeviceResult: Code/Swagger_docs/JsonDeviceResult.md
      - JsonExperimentByDateResult: Code/Swagger_docs/JsonExperimentByDateResult.md
      - JsonExperimentByOwnerResult: Code/Swagger_docs/JsonExperimentByOwnerResult.md
      - JsonExperimentIDResult: Code/Swagger_docs/JsonExperimentIDResult.md
      - JsonExperimentResult: Code/Swagger_docs/JsonExperimentResult.md
      - JsonFcImagingByIDResult: Code/Swagger_docs/JsonFcImagingByIDResult.md
      - JsonFcImagingResult: Code/Swagger_docs/JsonFcImagingResult.md
      - JsonFcLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonFcLeafParamByAnalyseIDResult.md
      - JsonFcLeafParamResult: Code/Swagger_docs/JsonFcLeafParamResult.md
      - JsonFcMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonFcMeasureExtendedDataByIDResult.md
      - JsonFcMeasureExtendedDataResult: Code/Swagger_docs/JsonFcMeasureExtendedDataResult.md
      - JsonFcParameterImageByAnalyseIDResult: Code/Swagger_docs/JsonFcParameterImageByAnalyseIDResult.md
      - JsonFcParameterImageResult: Code/Swagger_docs/JsonFcParameterImageResult.md
      - JsonFcParamResult: Code/Swagger_docs/JsonFcParamResult.md
      - JsonFcPlantMaskByMeasureIDResult: Code/Swagger_docs/JsonFcPlantMaskByMeasureIDResult.md
      - JsonFcPlantMaskResult: Code/Swagger_docs/JsonFcPlantMaskResult.md
      - JsonFcPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonFcPlantParamByAnalyseIDResult.md
      - JsonFcPlantParamResult: Code/Swagger_docs/JsonFcPlantParamResult.md
      - JsonFcUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonFcUsedParamByAnalyseIDResult.md
      - JsonFcUsedParamResult: Code/Swagger_docs/JsonFcUsedParamResult.md
      - JsonHcImagingByIDResult: Code/Swagger_docs/JsonHcImagingByIDResult.md
      - JsonHcImagingResult: Code/Swagger_docs/JsonHcImagingResult.md
      - JsonHcLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonHcLeafParamByAnalyseIDResult.md
      - JsonHcLeafParamResult: Code/Swagger_docs/JsonHcLeafParamResult.md
      - JsonHcMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonHcMeasureExtendedDataByIDResult.md
      - JsonHcMeasureExtendedDataResult: Code/Swagger_docs/JsonHcMeasureExtendedDataResult.md
      - JsonHcParameterImageByAnalyseIDResult: Code/Swagger_docs/JsonHcParameterImageByAnalyseIDResult.md
      - JsonHcParameterImageResult: Code/Swagger_docs/JsonHcParameterImageResult.md
      - JsonHcParamResult: Code/Swagger_docs/JsonHcParamResult.md
      - JsonHcPlantMaskByMeasureIDResult: Code/Swagger_docs/JsonHcPlantMaskByMeasureIDResult.md
      - JsonHcPlantMaskResult: Code/Swagger_docs/JsonHcPlantMaskResult.md
      - JsonHcPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonHcPlantParamByAnalyseIDResult.md
      - JsonHcPlantParamResult: Code/Swagger_docs/JsonHcPlantParamResult.md
      - JsonHcRgbImageByMeasureIDResult: Code/Swagger_docs/JsonHcRgbImageByMeasureIDResult.md
      - JsonHcRgbImageResult: Code/Swagger_docs/JsonHcRgbImageResult.md
      - JsonHcUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonHcUsedParamByAnalyseIDResult.md
      - JsonHcUsedParamResult: Code/Swagger_docs/JsonHcUsedParamResult.md
      - JsonIrImagingByIDResult: Code/Swagger_docs/JsonIrImagingByIDResult.md
      - JsonIrImagingResult: Code/Swagger_docs/JsonIrImagingResult.md
      - JsonIrLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonIrLeafParamByAnalyseIDResult.md
      - JsonIrLeafParamResult: Code/Swagger_docs/JsonIrLeafParamResult.md
      - JsonIrMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonIrMeasureExtendedDataByIDResult.md
      - JsonIrMeasureExtendedDataResult: Code/Swagger_docs/JsonIrMeasureExtendedDataResult.md
      - JsonIrParamResult: Code/Swagger_docs/JsonIrParamResult.md
      - JsonIrPlantMaskByMeasureIDResult: Code/Swagger_docs/JsonIrPlantMaskByMeasureIDResult.md
      - JsonIrPlantMaskImageByMeasureIDResult: Code/Swagger_docs/JsonIrPlantMaskImageByMeasureIDResult.md
      - JsonIrPlantMaskImageResult: Code/Swagger_docs/JsonIrPlantMaskImageResult.md
      - JsonIrPlantMaskResult: Code/Swagger_docs/JsonIrPlantMaskResult.md
      - JsonIrPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonIrPlantParamByAnalyseIDResult.md
      - JsonIrPlantParamResult: Code/Swagger_docs/JsonIrPlantParamResult.md
      - JsonIrUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonIrUsedParamByAnalyseIDResult.md
      - JsonIrUsedParamResult: Code/Swagger_docs/JsonIrUsedParamResult.md
      - JsonMscCalibrationByLightSetIDResult: Code/Swagger_docs/JsonMscCalibrationByLightSetIDResult.md
      - JsonMscCalibrationLightByIDResult: Code/Swagger_docs/JsonMscCalibrationLightByIDResult.md
      - JsonMscCalibrationLightResult: Code/Swagger_docs/JsonMscCalibrationLightResult.md
      - JsonMscCalibrationResult: Code/Swagger_docs/JsonMscCalibrationResult.md
      - JsonMscImagingByIDResult: Code/Swagger_docs/JsonMscImagingByIDResult.md
      - JsonMscImagingResult: Code/Swagger_docs/JsonMscImagingResult.md
      - JsonMscLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonMscLeafParamByAnalyseIDResult.md
      - JsonMscLeafParamResult: Code/Swagger_docs/JsonMscLeafParamResult.md
      - JsonMscLightSetResult: Code/Swagger_docs/JsonMscLightSetResult.md
      - JsonMscLightSetUsedResult: Code/Swagger_docs/JsonMscLightSetUsedResult.md
      - JsonMscMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonMscMeasureExtendedDataByIDResult.md
      - JsonMscMeasureExtendedDataResult: Code/Swagger_docs/JsonMscMeasureExtendedDataResult.md
      - JsonMscParameterImageByAnalyseIDResult: Code/Swagger_docs/JsonMscParameterImageByAnalyseIDResult.md
      - JsonMscParameterImageResult: Code/Swagger_docs/JsonMscParameterImageResult.md
      - JsonMscParamResult: Code/Swagger_docs/JsonMscParamResult.md
      - JsonMscPlantMaskByMeasureIDResult: Code/Swagger_docs/JsonMscPlantMaskByMeasureIDResult.md
      - JsonMscPlantMaskResult: Code/Swagger_docs/JsonMscPlantMaskResult.md
      - JsonMscPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonMscPlantParamByAnalyseIDResult.md
      - JsonMscPlantParamResult: Code/Swagger_docs/JsonMscPlantParamResult.md
      - JsonMscUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonMscUsedParamByAnalyseIDResult.md
      - JsonMscUsedParamResult: Code/Swagger_docs/JsonMscUsedParamResult.md
      - JsonNoteResult: Code/Swagger_docs/JsonNoteResult.md
      - JsonOwnerIDResult: Code/Swagger_docs/JsonOwnerIDResult.md
      - JsonOwnerResult: Code/Swagger_docs/JsonOwnerResult.md
      - JsonPlantByTrayIDAndDatesResult: Code/Swagger_docs/JsonPlantByTrayIDAndDatesResult.md
      - JsonPlantByTrayIDResult: Code/Swagger_docs/JsonPlantByTrayIDResult.md
      - JsonPlantByTrayProfileIDResult: Code/Swagger_docs/JsonPlantByTrayProfileIDResult.md
      - JsonPlantHeightByRoundIDResult: Code/Swagger_docs/JsonPlantHeightByRoundIDResult.md
      - JsonPlantLeavesByPlantAndTrayIDResult: Code/Swagger_docs/JsonPlantLeavesByPlantAndTrayIDResult.md
      - JsonPlantResult: Code/Swagger_docs/JsonPlantResult.md
      - JsonPlantWeightReferenceByPlantIDResult: Code/Swagger_docs/JsonPlantWeightReferenceByPlantIDResult.md
      - JsonPlantWeightReferenceByTrayIDResult: Code/Swagger_docs/JsonPlantWeightReferenceByTrayIDResult.md
      - JsonPlantWeightReferenceByTrayIDToDateResult: Code/Swagger_docs/JsonPlantWeightReferenceByTrayIDToDateResult.md
      - JsonProbeByIDResult: Code/Swagger_docs/JsonProbeByIDResult.md
      - JsonProbeResult: Code/Swagger_docs/JsonProbeResult.md
      - JsonProbeValueByDateResult: Code/Swagger_docs/JsonProbeValueByDateResult.md
      - JsonProbeValueByIDAndDateResult: Code/Swagger_docs/JsonProbeValueByIDAndDateResult.md
      - JsonRgbGreeningMaskImageByMeasureIDResult: Code/Swagger_docs/JsonRgbGreeningMaskImageByMeasureIDResult.md
      - JsonRgbGreeningMaskImageResult: Code/Swagger_docs/JsonRgbGreeningMaskImageResult.md
      - JsonRgbImagingByIDResult: Code/Swagger_docs/JsonRgbImagingByIDResult.md
      - JsonRgbImagingResult: Code/Swagger_docs/JsonRgbImagingResult.md
      - JsonRgbLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonRgbLeafParamByAnalyseIDResult.md
      - JsonRgbLeafParamColorByAnalyseIDResult: Code/Swagger_docs/JsonRgbLeafParamColorByAnalyseIDResult.md
      - JsonRgbLeafParamColorResult: Code/Swagger_docs/JsonRgbLeafParamColorResult.md
      - JsonRgbLeafParamResult: Code/Swagger_docs/JsonRgbLeafParamResult.md
      - JsonRgbMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonRgbMeasureExtendedDataByIDResult.md
      - JsonRgbMeasureExtendedDataResult: Code/Swagger_docs/JsonRgbMeasureExtendedDataResult.md
      - JsonRgbParamResult: Code/Swagger_docs/JsonRgbParamResult.md
      - JsonRgbPlantMaskByMeasureIDResult: Code/Swagger_docs/JsonRgbPlantMaskByMeasureIDResult.md
      - JsonRgbPlantMaskResult: Code/Swagger_docs/JsonRgbPlantMaskResult.md
      - JsonRgbPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonRgbPlantParamByAnalyseIDResult.md
      - JsonRgbPlantParamColorByAnalyseIDResult: Code/Swagger_docs/JsonRgbPlantParamColorByAnalyseIDResult.md
      - JsonRgbPlantParamColorResult: Code/Swagger_docs/JsonRgbPlantParamColorResult.md
      - JsonRgbPlantParamResult: Code/Swagger_docs/JsonRgbPlantParamResult.md
      - JsonRgbUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonRgbUsedParamByAnalyseIDResult.md
      - JsonRgbUsedParamColorByAnalyseIDResult: Code/Swagger_docs/JsonRgbUsedParamColorByAnalyseIDResult.md
      - JsonRgbUsedParamColorResult: Code/Swagger_docs/JsonRgbUsedParamColorResult.md
      - JsonRgbUsedParamsResult: Code/Swagger_docs/JsonRgbUsedParamsResult.md
      - JsonRoundByExperimentIDAndDateResult: Code/Swagger_docs/JsonRoundByExperimentIDAndDateResult.md
      - JsonRoundByExperimentIDResult: Code/Swagger_docs/JsonRoundByExperimentIDResult.md
      - JsonRoundOrderByExperimentIDAndDateResult: Code/Swagger_docs/JsonRoundOrderByExperimentIDAndDateResult.md
      - JsonRoundOrderByExperimentIDResult: Code/Swagger_docs/JsonRoundOrderByExperimentIDResult.md
      - JsonRoundOrderResult: Code/Swagger_docs/JsonRoundOrderResult.md
      - JsonRoundResult: Code/Swagger_docs/JsonRoundResult.md
      - JsonScalesMappingByTrayIDResult: Code/Swagger_docs/JsonScalesMappingByTrayIDResult.md
      - JsonScalesMeasureByIDResult: Code/Swagger_docs/JsonScalesMeasureByIDResult.md
      - JsonScalesMeasureResult: Code/Swagger_docs/JsonScalesMeasureResult.md
      - JsonScan3dAnalyzedModelByAnalyseIDResult: Code/Swagger_docs/JsonScan3dAnalyzedModelByAnalyseIDResult.md
      - JsonScan3dAnalyzedModelByMeasureIDResult: Code/Swagger_docs/JsonScan3dAnalyzedModelByMeasureIDResult.md
      - JsonScan3dAnalyzedModelResult: Code/Swagger_docs/JsonScan3dAnalyzedModelResult.md
      - JsonScan3dImagingByIDResult: Code/Swagger_docs/JsonScan3dImagingByIDResult.md
      - JsonScan3dImagingResult: Code/Swagger_docs/JsonScan3dImagingResult.md
      - JsonScan3dLeafParamByAnalyseIDResult: Code/Swagger_docs/JsonScan3dLeafParamByAnalyseIDResult.md
      - JsonScan3dLeafParamResult: Code/Swagger_docs/JsonScan3dLeafParamResult.md
      - JsonScan3dMeasureExtendedDataByIDResult: Code/Swagger_docs/JsonScan3dMeasureExtendedDataByIDResult.md
      - JsonScan3dMeasureExtendedDataResult: Code/Swagger_docs/JsonScan3dMeasureExtendedDataResult.md
      - JsonScan3dParamResult: Code/Swagger_docs/JsonScan3dParamResult.md
      - JsonScan3dPlantParamByAnalyseIDResult: Code/Swagger_docs/JsonScan3dPlantParamByAnalyseIDResult.md
      - JsonScan3dPlantParamResult: Code/Swagger_docs/JsonScan3dPlantParamResult.md
      - JsonScan3dUsedParamByAnalyseIDResult: Code/Swagger_docs/JsonScan3dUsedParamByAnalyseIDResult.md
      - JsonScan3dUsedParamResult: Code/Swagger_docs/JsonScan3dUsedParamResult.md
      - JsonSpectrumDeviceIDResult: Code/Swagger_docs/JsonSpectrumDeviceIDResult.md
      - JsonSpectrumDeviceResult: Code/Swagger_docs/JsonSpectrumDeviceResult.md
      - JsonSpectrumValuesResult: Code/Swagger_docs/JsonSpectrumValuesResult.md
      - JsonSprayActionResult: Code/Swagger_docs/JsonSprayActionResult.md
      - JsonSystemLogByLogTagAndDateResult: Code/Swagger_docs/JsonSystemLogByLogTagAndDateResult.md
      - JsonSystemLogByLogTypeAndDateResult: Code/Swagger_docs/JsonSystemLogByLogTypeAndDateResult.md
      - JsonSystemLogByRoundIDAndDateResult: Code/Swagger_docs/JsonSystemLogByRoundIDAndDateResult.md
      - JsonSystemLogByRoundIDResult: Code/Swagger_docs/JsonSystemLogByRoundIDResult.md
      - JsonSystemLogByTrayIDAndDateResult: Code/Swagger_docs/JsonSystemLogByTrayIDAndDateResult.md
      - JsonSystemLogByTrayIDResult: Code/Swagger_docs/JsonSystemLogByTrayIDResult.md
      - JsonSystemLogTagResult: Code/Swagger_docs/JsonSystemLogTagResult.md
      - JsonSystemLogTypeResult: Code/Swagger_docs/JsonSystemLogTypeResult.md
      - JsonSystemProfileActiveResult: Code/Swagger_docs/JsonSystemProfileActiveResult.md
      - JsonSystemProfileIDResult: Code/Swagger_docs/JsonSystemProfileIDResult.md
      - JsonSystemProfileResult: Code/Swagger_docs/JsonSystemProfileResult.md
      - JsonTrayByRoundIDResult: Code/Swagger_docs/JsonTrayByRoundIDResult.md
      - JsonTrayProfileByIDResult: Code/Swagger_docs/JsonTrayProfileByIDResult.md
      - JsonTrayProfileByTrayIDResult: Code/Swagger_docs/JsonTrayProfileByTrayIDResult.md
      - JsonTrayProfileByTrayIDToDateResult: Code/Swagger_docs/JsonTrayProfileByTrayIDToDateResult.md
      - JsonTrayResult: Code/Swagger_docs/JsonTrayResult.md
      - JsonTrayTypeByTrayIDResult: Code/Swagger_docs/JsonTrayTypeByTrayIDResult.md
      - JsonTrayTypeByTrayProfileIDResult: Code/Swagger_docs/JsonTrayTypeByTrayProfileIDResult.md
      - JsonTrayTypeResult: Code/Swagger_docs/JsonTrayTypeResult.md
      - JsonUsedTrayProfileByTrayIDResult: Code/Swagger_docs/JsonUsedTrayProfileByTrayIDResult.md
      - JsonVersionInfoResult: Code/Swagger_docs/JsonVersionInfoResult.md
      - LeafParameter: Code/Swagger_docs/LeafParameter.md
      - LogTag: Code/Swagger_docs/LogTag.md
      - LogType: Code/Swagger_docs/LogType.md
      - MeasureExtendedData: Code/Swagger_docs/MeasureExtendedData.md
      - MscApi: Code/Swagger_docs/MscApi.md
      - MscCalibration: Code/Swagger_docs/MscCalibration.md
      - MscCalibrationLight: Code/Swagger_docs/MscCalibrationLight.md
      - MscLightSet: Code/Swagger_docs/MscLightSet.md
      - Owner: Code/Swagger_docs/Owner.md
      - OwnerIDWrapper: Code/Swagger_docs/OwnerIDWrapper.md
      - Parameter: Code/Swagger_docs/Parameter.md
      - ParameterImage: Code/Swagger_docs/ParameterImage.md
      - Plant: Code/Swagger_docs/Plant.md
      - PlantApi: Code/Swagger_docs/PlantApi.md
      - PlantHeight: Code/Swagger_docs/PlantHeight.md
      - PlantLeaf: Code/Swagger_docs/PlantLeaf.md
      - PlantMask: Code/Swagger_docs/PlantMask.md
      - PlantParameter: Code/Swagger_docs/PlantParameter.md
      - PlantWeightReference: Code/Swagger_docs/PlantWeightReference.md
      - Probe: Code/Swagger_docs/Probe.md
      - ProbeApi: Code/Swagger_docs/ProbeApi.md
      - ProbeValue: Code/Swagger_docs/ProbeValue.md
      - ProfileApi: Code/Swagger_docs/ProfileApi.md
      - ProfileIDWrapper: Code/Swagger_docs/ProfileIDWrapper.md
      - RgbApi: Code/Swagger_docs/RgbApi.md
      - RgbGreeningMaskImage: Code/Swagger_docs/RgbGreeningMaskImage.md
      - Round: Code/Swagger_docs/Round.md
      - RoundApi: Code/Swagger_docs/RoundApi.md
      - RoundOrder: Code/Swagger_docs/RoundOrder.md
      - ScalesApi: Code/Swagger_docs/ScalesApi.md
      - ScalesData: Code/Swagger_docs/ScalesData.md
      - ScalesMapping: Code/Swagger_docs/ScalesMapping.md
      - Scan3DAnalyzedModel: Code/Swagger_docs/Scan3DAnalyzedModel.md
      - Scan3dApi: Code/Swagger_docs/Scan3dApi.md
      - Scan3DImaging: Code/Swagger_docs/Scan3DImaging.md
      - SpectrumDevice: Code/Swagger_docs/SpectrumDevice.md
      - SpectrumDeviceApi: Code/Swagger_docs/SpectrumDeviceApi.md
      - SpectrumDeviceID: Code/Swagger_docs/SpectrumDeviceID.md
      - SpectrumDeviceWavelengthsJSONWrapper: Code/Swagger_docs/SpectrumDeviceWavelengthsJSONWrapper.md
      - SpectrumValues: Code/Swagger_docs/SpectrumValues.md
      - SprayAction: Code/Swagger_docs/SprayAction.md
      - SprayApi: Code/Swagger_docs/SprayApi.md
      - StatisticLeafParameter: Code/Swagger_docs/StatisticLeafParameter.md
      - StatisticPlantParameter: Code/Swagger_docs/StatisticPlantParameter.md
      - SystemLog: Code/Swagger_docs/SystemLog.md
      - SystemLogApi: Code/Swagger_docs/SystemLogApi.md
      - SystemProfile: Code/Swagger_docs/SystemProfile.md
      - Tray: Code/Swagger_docs/Tray.md
      - TrayApi: Code/Swagger_docs/TrayApi.md
      - TrayProfile: Code/Swagger_docs/TrayProfile.md
      - TrayType: Code/Swagger_docs/TrayType.md
      - VersionInfo: Code/Swagger_docs/VersionInfo.md
      - VersionInfoApi: Code/Swagger_docs/VersionInfoApi.md

extra_css:
  - style.css

markdown_extensions:
- pymdownx.snippets:
    check_paths: true

plugins: 
- mkdocstrings