site_name: Documentation-Test
site_description: python documentation test

theme:
  name: material
repo_name: NPEC-NL/PSI-plantscreen-API
repo_url: https://github.com/NPEC-NL/PSI-plantscreen-API

nav:
  - README: README.md
  - Complete API Client: CompleteAPIClient.md
  - All API Endpoints: API_endpoints.md
  - All Models: Models.md
  - Api:
    - ActionApi: docs/ActionApi.md
    - BufferApi: docs/BufferApi.md
    - DeviceApi: docs/DeviceApi.md
    - ExperimentApi: docs/ExperimentApi.md
    - FcApi: docs/FcApi.md
    - FileApi: docs/FileApi.md
    - HcApi: docs/HcApi.md
    - IrApi: docs/IrApi.md
    - MscApi: docs/MscApi.md
    - PlantApi: docs/PlantApi.md
    - ProbeApi: docs/ProbeApi.md
    - ProfileApi: docs/ProfileApi.md
    - RgbApi: docs/RgbApi.md
    - RoundApi: docs/RoundApi.md
    - ScalesApi: docs/ScalesApi.md
    - Scan3dApi: docs/Scan3dApi.md
    - SpectrumDeviceApi: docs/SpectrumDeviceApi.md
    - SprayApi: docs/SprayApi.md
    - SystemLogApi: docs/SystemLogApi.md
    - TrayApi: docs/TrayApi.md
    - VersionInfoApi: docs/VersionInfoApi.md
  - Models:
      - Action: docs/Action.md
      - ActionGroup: docs/ActionGroup.md
      - ActionProtocol: docs/ActionProtocol.md
      - BufferHistory: docs/BufferHistory.md
      - Device: docs/Device.md
      - Experiment: docs/Experiment.md
      - ExperimentIDWrapper: docs/ExperimentIDWrapper.md
      - ExperimentNote: docs/ExperimentNote.md
      - FcImaging: docs/FcImaging.md
      - HcImaging: docs/HcImaging.md
      - HcRgbImage: docs/HcRgbImage.md
      - Imaging: docs/Imaging.md
      - LeafParameter: docs/LeafParameter.md
      - LogTag: docs/LogTag.md
      - LogType: docs/LogType.md
      - MeasureExtendedData: docs/MeasureExtendedData.md
      - MscCalibration: docs/MscCalibration.md
      - MscCalibrationLight: docs/MscCalibrationLight.md
      - MscCalibrationLight200Response: docs/MscCalibrationLight200Response.md
      - MscLightSet: docs/MscLightSet.md
      - Owner: docs/Owner.md
      - OwnerIDWrapper: docs/OwnerIDWrapper.md
      - Parameter: docs/Parameter.md
      - ParameterImage: docs/ParameterImage.md
      - Plant: docs/Plant.md
      - PlantHeight: docs/PlantHeight.md
      - PlantLeaf: docs/PlantLeaf.md
      - PlantMask: docs/PlantMask.md
      - PlantParameter: docs/PlantParameter.md
      - PlantWeightReference: docs/PlantWeightReference.md
      - Probe: docs/Probe.md
      - Probe200Response: docs/Probe200Response.md
      - ProbeValue: docs/ProbeValue.md
      - ProfileIDWrapper: docs/ProfileIDWrapper.md
      - RgbGreeningMaskImage: docs/RgbGreeningMaskImage.md
      - Round: docs/Round.md
      - RoundOrder: docs/RoundOrder.md
      - ScalesData: docs/ScalesData.md
      - ScalesMapping: docs/ScalesMapping.md
      - Scan3DAnalyzedModel: docs/Scan3DAnalyzedModel.md
      - Scan3DImaging: docs/Scan3DImaging.md
      - SpectrumDevice: docs/SpectrumDevice.md
      - SpectrumDeviceID: docs/SpectrumDeviceID.md
      - SpectrumDeviceWavelengthsJSONWrapper: docs/SpectrumDeviceWavelengthsJSONWrapper.md
      - SpectrumValues: docs/SpectrumValues.md
      - SprayAction: docs/SprayAction.md
      - StatisticLeafParameter: docs/StatisticLeafParameter.md
      - StatisticPlantParameter: docs/StatisticPlantParameter.md
      - SystemLog: docs/SystemLog.md
      - SystemProfile: docs/SystemProfile.md
      - Tray: docs/Tray.md
      - TrayProfile: docs/TrayProfile.md
      - TrayType: docs/TrayType.md
      - VersionInfo: docs/VersionInfo.md

extra_css:
  - style.css

markdown_extensions:
- pymdownx.snippets:
    check_paths: true

plugins: 
- mkdocstrings