# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import PrivateAttr

from typing import Optional, Set
from typing_extensions import Self


from plantscreen.models import action_group

from plantscreen.models import experiment


class Action(BaseModel):
    """
    Action
    """ # noqa: E501
    action_date_start: Optional[datetime] = Field(default=None, alias="ActionDateStart")
    action_done: Optional[StrictBool] = Field(default=None, alias="ActionDone")
    action_group_id: Optional[StrictInt] = Field(default=None, alias="ActionGroupID")
    _action_group: Optional[action_group.ActionGroup] = PrivateAttr(default=object())
    action_id: Optional[StrictInt] = Field(default=None, alias="ActionID")
    action_running: Optional[StrictBool] = Field(default=None, alias="ActionRunning")
    action_status: Optional[StrictStr] = Field(default=None, alias="ActionStatus")
    experiment_id: Optional[StrictInt] = Field(default=None, alias="ExperimentID")
    _experiment: Optional[experiment.Experiment] = PrivateAttr(default=object())

    __properties: ClassVar[List[str]] = ["ActionDateStart", "ActionDone", "ActionGroupID", "ActionID", "ActionRunning", "ActionStatus", "ExperimentID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    


    
    @property
    def action_group(self) -> action_group.ActionGroup:
        if type(self._action_group) is object:
            from plantscreen.api.action_api import ActionApi as Api
            json_result = Api().action_group(self.action_group_id)
            self._action_group = json_result.result
        return self._action_group




    
    @property
    def experiment(self) -> experiment.Experiment:
        if type(self._experiment) is object:
            from plantscreen.api.experiment_api import ExperimentApi as Api
            json_result = Api().experiment(self.experiment_id)
            self._experiment = json_result.result
        return self._experiment


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Action from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Action from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            
            "ActionDateStart": obj.get("ActionDateStart") or None,
                        "ActionDone": obj.get("ActionDone"),
                        "ActionGroupID": obj.get("ActionGroupID"),
                        "ActionID": obj.get("ActionID"),
                        "ActionRunning": obj.get("ActionRunning"),
                        "ActionStatus": obj.get("ActionStatus"),
                        "ExperimentID": obj.get("ExperimentID")
        })
        return _obj


