# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional

from typing import Optional, Set
from typing_extensions import Self

from pydantic import PrivateAttr


from plantscreen.models import device

from plantscreen.models import round

from plantscreen.models import tray


class MeasureExtendedData(BaseModel):
    """
    MeasureExtendedData
    """ # noqa: E501
    device_id: Optional[StrictInt] = Field(default=None, alias="DeviceID")
    _device: Optional[device.Device] = PrivateAttr(default=object())
    extended_data: Optional[StrictStr] = Field(default=None, alias="ExtendedData", json_schema_extra={"examples": ["<DataSet> <Item name=\"latitude\" type=\"double\" unit=\"degree\">49.33948096</Item> <Item name=\"longitude\" type=\"double\" unit=\"degree\">16.47611234</Item> <Item name=\"distanceToWantedPoint\" type=\"double\" unit=\"meters\">0.46</Item> <Item name=\"speed\" type=\"double\" unit=\"km/h\">0.4</Item> </DataSet>"]})
    measure_date: Optional[datetime] = Field(default=None, alias="MeasureDate")
    measure_id: Optional[StrictInt] = Field(default=None, alias="MeasureID")
    round_id: Optional[StrictInt] = Field(default=None, alias="RoundID")
    _round: Optional[round.Round] = PrivateAttr(default=object())
    tray_id: Optional[StrictInt] = Field(default=None, alias="TrayID")
    _tray: Optional[tray.Tray] = PrivateAttr(default=object())

    __properties: ClassVar[List[str]] = ["DeviceID", "ExtendedData", "MeasureDate", "MeasureID", "RoundID", "TrayID"]

    @field_validator('measure_date')
    def measure_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        #! Pydantic may pass a datetime object here (already parsed),
        # while this regex applies only to raw string input.
        if not isinstance(value, str):
            return value

        if not re.match(r"^([0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|[3][0-1]) ([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9]))$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|[3][0-1]) ([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9]))$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    
    
    @property
    def device(self) -> device.Device:
        if type(self._device) is object:
            from plantscreen.api.device_api import DeviceApi as Api
            json_result = Api().device(self.device_id)
            self._device = json_result.result
        return self._device




    
    @property
    def round(self) -> round.Round:
        if type(self._round) is object:
            from plantscreen.api.round_api import RoundApi as Api
            json_result = Api().round(self.round_id)
            self._round = json_result.result
        return self._round

    
    @property
    def tray(self) -> tray.Tray:
        if type(self._tray) is object:
            from plantscreen.api.tray_api import TrayApi as Api
            json_result = Api().tray(self.tray_id)
            self._tray = json_result.result
        return self._tray


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasureExtendedData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasureExtendedData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
                        "DeviceID": obj.get("DeviceID"),
                        "ExtendedData": obj.get("ExtendedData"),
            
            "MeasureDate": obj.get("MeasureDate") or None,
                        "MeasureID": obj.get("MeasureID"),
                        "RoundID": obj.get("RoundID"),
                        "TrayID": obj.get("TrayID")
        })
        return _obj


