# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import PrivateAttr
from typing import Optional, Set
from typing_extensions import Self




class MscCalibration(BaseModel):
    """
    MscCalibration
    """ # noqa: E501
    calibration_date: Optional[datetime] = Field(default=None, alias="CalibrationDate")
    calibration_id: Optional[StrictInt] = Field(default=None, alias="CalibrationID")
    calibration_image_path: Optional[StrictStr] = Field(default=None, description="filetype", alias="CalibrationImagePath")
    camera_exposure: Optional[StrictInt] = Field(default=None, alias="CameraExposure")
    camera_gain: Optional[StrictInt] = Field(default=None, alias="CameraGain")
    light_set_id: Optional[StrictInt] = Field(default=None, alias="LightSetID")

    __properties: ClassVar[List[str]] = ["CalibrationDate", "CalibrationID", "CalibrationImagePath", "CameraExposure", "CameraGain", "LightSetID"]

    @field_validator('calibration_date')
    def calibration_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        #! Pydantic may pass a datetime object here (already parsed),
        # while this regex applies only to raw string input.
        if not isinstance(value, str):
            return value

        if not re.match(r"^([0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|[3][0-1]) ([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9]))$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]{4}-([0][0-9]|[1][0-2])-([0-2][0-9]|[3][0-1]) ([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9]))$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    







    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MscCalibration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MscCalibration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            
            "CalibrationDate": obj.get("CalibrationDate") or None,
                        "CalibrationID": obj.get("CalibrationID"),
                        "CalibrationImagePath": obj.get("CalibrationImagePath"),
                        "CameraExposure": obj.get("CameraExposure"),
                        "CameraGain": obj.get("CameraGain"),
                        "LightSetID": obj.get("LightSetID")
        })
        return _obj


