# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import PrivateAttr
from typing import Optional, Set
from typing_extensions import Self




from plantscreen.models import experiment

class Owner(BaseModel):
    """
    Owner
    """ # noqa: E501
    create_date: Optional[datetime] = Field(default=None, alias="CreateDate")
    email: Optional[StrictStr] = Field(default=None, alias="Email")
    first_name: Optional[StrictStr] = Field(default=None, alias="FirstName")
    last_failed_date: Optional[datetime] = Field(default=None, alias="LastFailedDate")
    last_name: Optional[StrictStr] = Field(default=None, alias="LastName")
    last_success_login: Optional[datetime] = Field(default=None, alias="LastSuccessLogin")
    login: Optional[StrictStr] = Field(default=None, alias="Login")
    owner_id: Optional[StrictInt] = Field(default=None, alias="OwnerID")
    sms_phone_number: Optional[StrictStr] = Field(default=None, alias="SmsPhoneNumber")
    _experiments: Optional[List[experiment.Experiment]] = PrivateAttr(default=object())

    __properties: ClassVar[List[str]] = ["CreateDate", "Email", "FirstName", "LastFailedDate", "LastName", "LastSuccessLogin", "Login", "OwnerID", "SmsPhoneNumber"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    








    
    @property
    def experiments(self) -> List[experiment.Experiment]:
        if type(self._experiments) is object:
            from plantscreen.api.experiment_api import ExperimentApi as Api
            json_result = Api().experiment_owner(id=self.owner_id)
            self._experiments = json_result.result
        return self._experiments
    
    


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Owner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Owner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            
            "CreateDate": obj.get("CreateDate") or None,
                        "Email": obj.get("Email"),
                        "FirstName": obj.get("FirstName"),
            
            "LastFailedDate": obj.get("LastFailedDate") or None,
                        "LastName": obj.get("LastName"),
            
            "LastSuccessLogin": obj.get("LastSuccessLogin") or None,
                        "Login": obj.get("Login"),
                        "OwnerID": obj.get("OwnerID"),
                        "SmsPhoneNumber": obj.get("SmsPhoneNumber")
        })
        return _obj


