# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional

from typing import Optional, Set
from typing_extensions import Self

from pydantic import PrivateAttr


from plantscreen.models import device

from plantscreen.models import experiment

from plantscreen.models import round

from plantscreen.models import tray


class ParameterImage(BaseModel):
    """
    ParameterImage
    """ # noqa: E501
    analyse_id: Optional[StrictInt] = Field(default=None, alias="AnalyseID")
    device_id: Optional[StrictInt] = Field(default=None, alias="DeviceID")
    _device: Optional[device.Device] = PrivateAttr(default=object())
    device_pid: Optional[StrictStr] = Field(default=None, alias="DevicePID")
    experiment_id: Optional[StrictInt] = Field(default=None, alias="ExperimentID")
    _experiment: Optional[experiment.Experiment] = PrivateAttr(default=object())
    measure_angle: Optional[StrictInt] = Field(default=None, alias="MeasureAngle")
    measure_id: Optional[StrictInt] = Field(default=None, alias="MeasureID")
    parameter_id: Optional[StrictInt] = Field(default=None, alias="ParameterID")
    parameter_image_path: Optional[StrictStr] = Field(default=None, description="filetype", alias="ParameterImagePath")
    parameter_name: Optional[StrictStr] = Field(default=None, alias="ParameterName")
    round_id: Optional[StrictInt] = Field(default=None, alias="RoundID")
    _round: Optional[round.Round] = PrivateAttr(default=object())
    tray_barcode: Optional[StrictStr] = Field(default=None, alias="TrayBarcode")
    tray_id: Optional[StrictInt] = Field(default=None, alias="TrayID")
    _tray: Optional[tray.Tray] = PrivateAttr(default=object())

    __properties: ClassVar[List[str]] = ["AnalyseID", "DeviceID", "DevicePID", "ExperimentID", "MeasureAngle", "MeasureID", "ParameterID", "ParameterImagePath", "ParameterName", "RoundID", "TrayBarcode", "TrayID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    

    
    @property
    def device(self) -> device.Device:
        if type(self._device) is object:
            from plantscreen.api.device_api import DeviceApi as Api
            json_result = Api().device(self.device_id)
            self._device = json_result.result
        return self._device


    
    @property
    def experiment(self) -> experiment.Experiment:
        if type(self._experiment) is object:
            from plantscreen.api.experiment_api import ExperimentApi as Api
            json_result = Api().experiment(self.experiment_id)
            self._experiment = json_result.result
        return self._experiment






    
    @property
    def round(self) -> round.Round:
        if type(self._round) is object:
            from plantscreen.api.round_api import RoundApi as Api
            json_result = Api().round(self.round_id)
            self._round = json_result.result
        return self._round


    
    @property
    def tray(self) -> tray.Tray:
        if type(self._tray) is object:
            from plantscreen.api.tray_api import TrayApi as Api
            json_result = Api().tray(self.tray_id)
            self._tray = json_result.result
        return self._tray


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ParameterImage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ParameterImage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
                        "AnalyseID": obj.get("AnalyseID"),
                        "DeviceID": obj.get("DeviceID"),
                        "DevicePID": obj.get("DevicePID"),
                        "ExperimentID": obj.get("ExperimentID"),
                        "MeasureAngle": obj.get("MeasureAngle"),
                        "MeasureID": obj.get("MeasureID"),
                        "ParameterID": obj.get("ParameterID"),
                        "ParameterImagePath": obj.get("ParameterImagePath"),
                        "ParameterName": obj.get("ParameterName"),
                        "RoundID": obj.get("RoundID"),
                        "TrayBarcode": obj.get("TrayBarcode"),
                        "TrayID": obj.get("TrayID")
        })
        return _obj


