# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SystemLog(BaseModel):
    """
    SystemLog
    """ # noqa: E501
    experiment_id: Optional[StrictInt] = Field(default=None, alias="ExperimentID")
    log_date: Optional[datetime] = Field(default=None, alias="LogDate")
    log_id: Optional[StrictInt] = Field(default=None, alias="LogID")
    log_tag: Optional[StrictStr] = Field(default=None, alias="LogTag")
    log_text: Optional[StrictStr] = Field(default=None, alias="LogText")
    log_type: Optional[StrictStr] = Field(default=None, alias="LogType")
    round_id: Optional[StrictInt] = Field(default=None, alias="RoundID")
    tray_barcode: Optional[StrictStr] = Field(default=None, alias="TrayBarcode")
    tray_id: Optional[StrictInt] = Field(default=None, alias="TrayID")
    tray_profile_id: Optional[StrictInt] = Field(default=None, alias="TrayProfileID")
    __properties: ClassVar[List[str]] = ["ExperimentID", "LogDate", "LogID", "LogTag", "LogText", "LogType", "RoundID", "TrayBarcode", "TrayID", "TrayProfileID"]

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ExperimentID": obj.get("ExperimentID"),
            "LogDate": obj.get("LogDate"),
            "LogID": obj.get("LogID"),
            "LogTag": obj.get("LogTag"),
            "LogText": obj.get("LogText"),
            "LogType": obj.get("LogType"),
            "RoundID": obj.get("RoundID"),
            "TrayBarcode": obj.get("TrayBarcode"),
            "TrayID": obj.get("TrayID"),
            "TrayProfileID": obj.get("TrayProfileID")
        })
        return _obj


