# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional

from typing import Optional, Set
from typing_extensions import Self

from pydantic import PrivateAttr



from plantscreen.models import device

class SystemProfile(BaseModel):
    """
    SystemProfile
    """ # noqa: E501
    profile_active: Optional[StrictBool] = Field(default=None, alias="ProfileActive")
    profile_id: Optional[StrictInt] = Field(default=None, alias="ProfileID")
    profile_info: Optional[StrictStr] = Field(default=None, alias="ProfileInfo")
    profile_name: Optional[StrictStr] = Field(default=None, alias="ProfileName")
    system_hw_config: Optional[StrictStr] = Field(default=None, alias="SystemHwConfig", json_schema_extra={"examples": ["\"<?xml version=\"1.0\" encoding=\"utf-8\" ?> <Configuration> <TrayStack> <RowCount>9</RowCount> <RowCapacity>30</RowCapacity> </TrayStack> <AdaptChamber>true</AdaptChamber> <HeightMeasurement>true</HeightMeasurement> <Commands> <SetLight>true</SetLight> <TrayLoad>true</TrayLoad> <TraySwap>true</TraySwap><TrayUnload>false</TrayUnload> <Measure>true</Measure> </Commands> <Lights> <Lightcaption=\"Load\">LightLoad</Light> <Light caption=\"White\">LightMain1</Light> <Light caption=\"Red\">LightMain2</Light> <Light caption=\"IR\">LightMain3</Light> </Lights> <Pids> <PID name=\"RGBM\" caption=\"RGBM\"> <View>Side</View> <Turntable>true</Turntable> <AxisZ heightVisible=\"false\">true</AxisZ> </PID> </Pids> <Analyse> </Analyse> </Configuration>"]})
    _devices: Optional[List[device.Device]] = PrivateAttr(default=object())

    __properties: ClassVar[List[str]] = ["ProfileActive", "ProfileID", "ProfileInfo", "ProfileName", "SystemHwConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    




    
    @property
    def devices(self) -> List[device.Device]:
        if type(self._devices) is object:
            from plantscreen.api.device_api import DeviceApi as Api
            json_result = Api().device_profile(id=self.profile_id)
            self._devices = json_result.result
        return self._devices
    
    


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
                        "ProfileActive": obj.get("ProfileActive"),
                        "ProfileID": obj.get("ProfileID"),
                        "ProfileInfo": obj.get("ProfileInfo"),
                        "ProfileName": obj.get("ProfileName"),
                        "SystemHwConfig": obj.get("SystemHwConfig")
        })
        return _obj


