# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Device(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_caption': 'str',
        'device_config': 'str',
        'device_family': 'str',
        'device_id': 'int',
        'device_name': 'str',
        'device_pid': 'str',
        'device_type': 'str',
        'device_validity_start': 'datetime',
        'device_validity_end': 'datetime',
        'profile_id': 'int'
    }

    attribute_map = {
        'device_caption': 'DeviceCaption',
        'device_config': 'DeviceConfig',
        'device_family': 'DeviceFamily',
        'device_id': 'DeviceID',
        'device_name': 'DeviceName',
        'device_pid': 'DevicePID',
        'device_type': 'DeviceType',
        'device_validity_start': 'DeviceValidityStart',
        'device_validity_end': 'DeviceValidityEnd',
        'profile_id': 'ProfileID'
    }

    def __init__(self, device_caption=None, device_config=None, device_family=None, device_id=None, device_name=None, device_pid=None, device_type=None, device_validity_start=None, device_validity_end=None, profile_id=None):  # noqa: E501
        """Device - a model defined in Swagger"""  # noqa: E501
        self._device_caption = None
        self._device_config = None
        self._device_family = None
        self._device_id = None
        self._device_name = None
        self._device_pid = None
        self._device_type = None
        self._device_validity_start = None
        self._device_validity_end = None
        self._profile_id = None
        self.discriminator = None
        if device_caption is not None:
            self.device_caption = device_caption
        if device_config is not None:
            self.device_config = device_config
        if device_family is not None:
            self.device_family = device_family
        if device_id is not None:
            self.device_id = device_id
        if device_name is not None:
            self.device_name = device_name
        if device_pid is not None:
            self.device_pid = device_pid
        if device_type is not None:
            self.device_type = device_type
        if device_validity_start is not None:
            self.device_validity_start = device_validity_start
        if device_validity_end is not None:
            self.device_validity_end = device_validity_end
        if profile_id is not None:
            self.profile_id = profile_id

    @property
    def device_caption(self):
        """Gets the device_caption of this Device.  # noqa: E501


        :return: The device_caption of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_caption

    @device_caption.setter
    def device_caption(self, device_caption):
        """Sets the device_caption of this Device.


        :param device_caption: The device_caption of this Device.  # noqa: E501
        :type: str
        """

        self._device_caption = device_caption

    @property
    def device_config(self):
        """Gets the device_config of this Device.  # noqa: E501


        :return: The device_config of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_config

    @device_config.setter
    def device_config(self, device_config):
        """Sets the device_config of this Device.


        :param device_config: The device_config of this Device.  # noqa: E501
        :type: str
        """

        self._device_config = device_config

    @property
    def device_family(self):
        """Gets the device_family of this Device.  # noqa: E501


        :return: The device_family of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_family

    @device_family.setter
    def device_family(self, device_family):
        """Sets the device_family of this Device.


        :param device_family: The device_family of this Device.  # noqa: E501
        :type: str
        """

        self._device_family = device_family

    @property
    def device_id(self):
        """Gets the device_id of this Device.  # noqa: E501


        :return: The device_id of this Device.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this Device.


        :param device_id: The device_id of this Device.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def device_name(self):
        """Gets the device_name of this Device.  # noqa: E501


        :return: The device_name of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this Device.


        :param device_name: The device_name of this Device.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def device_pid(self):
        """Gets the device_pid of this Device.  # noqa: E501


        :return: The device_pid of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_pid

    @device_pid.setter
    def device_pid(self, device_pid):
        """Sets the device_pid of this Device.


        :param device_pid: The device_pid of this Device.  # noqa: E501
        :type: str
        """

        self._device_pid = device_pid

    @property
    def device_type(self):
        """Gets the device_type of this Device.  # noqa: E501


        :return: The device_type of this Device.  # noqa: E501
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this Device.


        :param device_type: The device_type of this Device.  # noqa: E501
        :type: str
        """

        self._device_type = device_type

    @property
    def device_validity_start(self):
        """Gets the device_validity_start of this Device.  # noqa: E501


        :return: The device_validity_start of this Device.  # noqa: E501
        :rtype: datetime
        """
        return self._device_validity_start

    @device_validity_start.setter
    def device_validity_start(self, device_validity_start):
        """Sets the device_validity_start of this Device.


        :param device_validity_start: The device_validity_start of this Device.  # noqa: E501
        :type: datetime
        """

        self._device_validity_start = device_validity_start

    @property
    def device_validity_end(self):
        """Gets the device_validity_end of this Device.  # noqa: E501


        :return: The device_validity_end of this Device.  # noqa: E501
        :rtype: datetime
        """
        return self._device_validity_end

    @device_validity_end.setter
    def device_validity_end(self, device_validity_end):
        """Sets the device_validity_end of this Device.


        :param device_validity_end: The device_validity_end of this Device.  # noqa: E501
        :type: datetime
        """

        self._device_validity_end = device_validity_end

    @property
    def profile_id(self):
        """Gets the profile_id of this Device.  # noqa: E501


        :return: The profile_id of this Device.  # noqa: E501
        :rtype: int
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id):
        """Sets the profile_id of this Device.


        :param profile_id: The profile_id of this Device.  # noqa: E501
        :type: int
        """

        self._profile_id = profile_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Device, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Device):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
