# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FcImaging(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_id': 'int',
        'device_id': 'int',
        'device_pid': 'str',
        'experiment_id': 'int',
        'measure_angle': 'int',
        'measure_date': 'datetime',
        'measure_height': 'int',
        'measure_id': 'int',
        'protocol_path': 'str',
        'round_id': 'int',
        'tray_barcode': 'str',
        'tray_id': 'int',
        'tray_profile_id': 'int',
        'tar_path': 'str'
    }

    attribute_map = {
        'action_id': 'ActionID',
        'device_id': 'DeviceID',
        'device_pid': 'DevicePID',
        'experiment_id': 'ExperimentID',
        'measure_angle': 'MeasureAngle',
        'measure_date': 'MeasureDate',
        'measure_height': 'MeasureHeight',
        'measure_id': 'MeasureID',
        'protocol_path': 'ProtocolPath',
        'round_id': 'RoundID',
        'tray_barcode': 'TrayBarcode',
        'tray_id': 'TrayID',
        'tray_profile_id': 'TrayProfileID',
        'tar_path': 'TarPath'
    }

    def __init__(self, action_id=None, device_id=None, device_pid=None, experiment_id=None, measure_angle=None, measure_date=None, measure_height=None, measure_id=None, protocol_path=None, round_id=None, tray_barcode=None, tray_id=None, tray_profile_id=None, tar_path=None):  # noqa: E501
        """FcImaging - a model defined in Swagger"""  # noqa: E501
        self._action_id = None
        self._device_id = None
        self._device_pid = None
        self._experiment_id = None
        self._measure_angle = None
        self._measure_date = None
        self._measure_height = None
        self._measure_id = None
        self._protocol_path = None
        self._round_id = None
        self._tray_barcode = None
        self._tray_id = None
        self._tray_profile_id = None
        self._tar_path = None
        self.discriminator = None
        if action_id is not None:
            self.action_id = action_id
        if device_id is not None:
            self.device_id = device_id
        if device_pid is not None:
            self.device_pid = device_pid
        if experiment_id is not None:
            self.experiment_id = experiment_id
        if measure_angle is not None:
            self.measure_angle = measure_angle
        if measure_date is not None:
            self.measure_date = measure_date
        if measure_height is not None:
            self.measure_height = measure_height
        if measure_id is not None:
            self.measure_id = measure_id
        if protocol_path is not None:
            self.protocol_path = protocol_path
        if round_id is not None:
            self.round_id = round_id
        if tray_barcode is not None:
            self.tray_barcode = tray_barcode
        if tray_id is not None:
            self.tray_id = tray_id
        if tray_profile_id is not None:
            self.tray_profile_id = tray_profile_id
        if tar_path is not None:
            self.tar_path = tar_path

    @property
    def action_id(self):
        """Gets the action_id of this FcImaging.  # noqa: E501


        :return: The action_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this FcImaging.


        :param action_id: The action_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._action_id = action_id

    @property
    def device_id(self):
        """Gets the device_id of this FcImaging.  # noqa: E501


        :return: The device_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this FcImaging.


        :param device_id: The device_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def device_pid(self):
        """Gets the device_pid of this FcImaging.  # noqa: E501


        :return: The device_pid of this FcImaging.  # noqa: E501
        :rtype: str
        """
        return self._device_pid

    @device_pid.setter
    def device_pid(self, device_pid):
        """Sets the device_pid of this FcImaging.


        :param device_pid: The device_pid of this FcImaging.  # noqa: E501
        :type: str
        """

        self._device_pid = device_pid

    @property
    def experiment_id(self):
        """Gets the experiment_id of this FcImaging.  # noqa: E501


        :return: The experiment_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._experiment_id

    @experiment_id.setter
    def experiment_id(self, experiment_id):
        """Sets the experiment_id of this FcImaging.


        :param experiment_id: The experiment_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._experiment_id = experiment_id

    @property
    def measure_angle(self):
        """Gets the measure_angle of this FcImaging.  # noqa: E501


        :return: The measure_angle of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._measure_angle

    @measure_angle.setter
    def measure_angle(self, measure_angle):
        """Sets the measure_angle of this FcImaging.


        :param measure_angle: The measure_angle of this FcImaging.  # noqa: E501
        :type: int
        """

        self._measure_angle = measure_angle

    @property
    def measure_date(self):
        """Gets the measure_date of this FcImaging.  # noqa: E501


        :return: The measure_date of this FcImaging.  # noqa: E501
        :rtype: datetime
        """
        return self._measure_date

    @measure_date.setter
    def measure_date(self, measure_date):
        """Sets the measure_date of this FcImaging.


        :param measure_date: The measure_date of this FcImaging.  # noqa: E501
        :type: datetime
        """

        self._measure_date = measure_date

    @property
    def measure_height(self):
        """Gets the measure_height of this FcImaging.  # noqa: E501


        :return: The measure_height of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._measure_height

    @measure_height.setter
    def measure_height(self, measure_height):
        """Sets the measure_height of this FcImaging.


        :param measure_height: The measure_height of this FcImaging.  # noqa: E501
        :type: int
        """

        self._measure_height = measure_height

    @property
    def measure_id(self):
        """Gets the measure_id of this FcImaging.  # noqa: E501


        :return: The measure_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._measure_id

    @measure_id.setter
    def measure_id(self, measure_id):
        """Sets the measure_id of this FcImaging.


        :param measure_id: The measure_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._measure_id = measure_id

    @property
    def protocol_path(self):
        """Gets the protocol_path of this FcImaging.  # noqa: E501

        filetype  # noqa: E501

        :return: The protocol_path of this FcImaging.  # noqa: E501
        :rtype: str
        """
        return self._protocol_path

    @protocol_path.setter
    def protocol_path(self, protocol_path):
        """Sets the protocol_path of this FcImaging.

        filetype  # noqa: E501

        :param protocol_path: The protocol_path of this FcImaging.  # noqa: E501
        :type: str
        """

        self._protocol_path = protocol_path

    @property
    def round_id(self):
        """Gets the round_id of this FcImaging.  # noqa: E501


        :return: The round_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._round_id

    @round_id.setter
    def round_id(self, round_id):
        """Sets the round_id of this FcImaging.


        :param round_id: The round_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._round_id = round_id

    @property
    def tray_barcode(self):
        """Gets the tray_barcode of this FcImaging.  # noqa: E501


        :return: The tray_barcode of this FcImaging.  # noqa: E501
        :rtype: str
        """
        return self._tray_barcode

    @tray_barcode.setter
    def tray_barcode(self, tray_barcode):
        """Sets the tray_barcode of this FcImaging.


        :param tray_barcode: The tray_barcode of this FcImaging.  # noqa: E501
        :type: str
        """

        self._tray_barcode = tray_barcode

    @property
    def tray_id(self):
        """Gets the tray_id of this FcImaging.  # noqa: E501


        :return: The tray_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._tray_id

    @tray_id.setter
    def tray_id(self, tray_id):
        """Sets the tray_id of this FcImaging.


        :param tray_id: The tray_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._tray_id = tray_id

    @property
    def tray_profile_id(self):
        """Gets the tray_profile_id of this FcImaging.  # noqa: E501


        :return: The tray_profile_id of this FcImaging.  # noqa: E501
        :rtype: int
        """
        return self._tray_profile_id

    @tray_profile_id.setter
    def tray_profile_id(self, tray_profile_id):
        """Sets the tray_profile_id of this FcImaging.


        :param tray_profile_id: The tray_profile_id of this FcImaging.  # noqa: E501
        :type: int
        """

        self._tray_profile_id = tray_profile_id

    @property
    def tar_path(self):
        """Gets the tar_path of this FcImaging.  # noqa: E501

        filetype  # noqa: E501

        :return: The tar_path of this FcImaging.  # noqa: E501
        :rtype: str
        """
        return self._tar_path

    @tar_path.setter
    def tar_path(self, tar_path):
        """Sets the tar_path of this FcImaging.

        filetype  # noqa: E501

        :param tar_path: The tar_path of this FcImaging.  # noqa: E501
        :type: str
        """

        self._tar_path = tar_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FcImaging, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FcImaging):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
