# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MscCalibrationLight(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'calibration_light_id': 'int',
        'calibration_id': 'int',
        'light_set_id': 'int',
        'calibration_light_level': 'int',
        'light_id': 'int',
        'light_caption': 'str'
    }

    attribute_map = {
        'calibration_light_id': 'CalibrationLightID',
        'calibration_id': 'CalibrationID',
        'light_set_id': 'LightSetID',
        'calibration_light_level': 'CalibrationLightLevel',
        'light_id': 'LightID',
        'light_caption': 'LightCaption'
    }

    def __init__(self, calibration_light_id=None, calibration_id=None, light_set_id=None, calibration_light_level=None, light_id=None, light_caption=None):  # noqa: E501
        """MscCalibrationLight - a model defined in Swagger"""  # noqa: E501
        self._calibration_light_id = None
        self._calibration_id = None
        self._light_set_id = None
        self._calibration_light_level = None
        self._light_id = None
        self._light_caption = None
        self.discriminator = None
        if calibration_light_id is not None:
            self.calibration_light_id = calibration_light_id
        if calibration_id is not None:
            self.calibration_id = calibration_id
        if light_set_id is not None:
            self.light_set_id = light_set_id
        if calibration_light_level is not None:
            self.calibration_light_level = calibration_light_level
        if light_id is not None:
            self.light_id = light_id
        if light_caption is not None:
            self.light_caption = light_caption

    @property
    def calibration_light_id(self):
        """Gets the calibration_light_id of this MscCalibrationLight.  # noqa: E501


        :return: The calibration_light_id of this MscCalibrationLight.  # noqa: E501
        :rtype: int
        """
        return self._calibration_light_id

    @calibration_light_id.setter
    def calibration_light_id(self, calibration_light_id):
        """Sets the calibration_light_id of this MscCalibrationLight.


        :param calibration_light_id: The calibration_light_id of this MscCalibrationLight.  # noqa: E501
        :type: int
        """

        self._calibration_light_id = calibration_light_id

    @property
    def calibration_id(self):
        """Gets the calibration_id of this MscCalibrationLight.  # noqa: E501


        :return: The calibration_id of this MscCalibrationLight.  # noqa: E501
        :rtype: int
        """
        return self._calibration_id

    @calibration_id.setter
    def calibration_id(self, calibration_id):
        """Sets the calibration_id of this MscCalibrationLight.


        :param calibration_id: The calibration_id of this MscCalibrationLight.  # noqa: E501
        :type: int
        """

        self._calibration_id = calibration_id

    @property
    def light_set_id(self):
        """Gets the light_set_id of this MscCalibrationLight.  # noqa: E501


        :return: The light_set_id of this MscCalibrationLight.  # noqa: E501
        :rtype: int
        """
        return self._light_set_id

    @light_set_id.setter
    def light_set_id(self, light_set_id):
        """Sets the light_set_id of this MscCalibrationLight.


        :param light_set_id: The light_set_id of this MscCalibrationLight.  # noqa: E501
        :type: int
        """

        self._light_set_id = light_set_id

    @property
    def calibration_light_level(self):
        """Gets the calibration_light_level of this MscCalibrationLight.  # noqa: E501


        :return: The calibration_light_level of this MscCalibrationLight.  # noqa: E501
        :rtype: int
        """
        return self._calibration_light_level

    @calibration_light_level.setter
    def calibration_light_level(self, calibration_light_level):
        """Sets the calibration_light_level of this MscCalibrationLight.


        :param calibration_light_level: The calibration_light_level of this MscCalibrationLight.  # noqa: E501
        :type: int
        """

        self._calibration_light_level = calibration_light_level

    @property
    def light_id(self):
        """Gets the light_id of this MscCalibrationLight.  # noqa: E501


        :return: The light_id of this MscCalibrationLight.  # noqa: E501
        :rtype: int
        """
        return self._light_id

    @light_id.setter
    def light_id(self, light_id):
        """Sets the light_id of this MscCalibrationLight.


        :param light_id: The light_id of this MscCalibrationLight.  # noqa: E501
        :type: int
        """

        self._light_id = light_id

    @property
    def light_caption(self):
        """Gets the light_caption of this MscCalibrationLight.  # noqa: E501


        :return: The light_caption of this MscCalibrationLight.  # noqa: E501
        :rtype: str
        """
        return self._light_caption

    @light_caption.setter
    def light_caption(self, light_caption):
        """Sets the light_caption of this MscCalibrationLight.


        :param light_caption: The light_caption of this MscCalibrationLight.  # noqa: E501
        :type: str
        """

        self._light_caption = light_caption

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MscCalibrationLight, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MscCalibrationLight):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
