# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Owner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner_id': 'int',
        'login': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'sms_phone_number': 'str',
        'create_date': 'datetime',
        'last_success_login': 'datetime',
        'last_failed_date': 'datetime'
    }

    attribute_map = {
        'owner_id': 'OwnerID',
        'login': 'Login',
        'first_name': 'FirstName',
        'last_name': 'LastName',
        'email': 'Email',
        'sms_phone_number': 'SmsPhoneNumber',
        'create_date': 'CreateDate',
        'last_success_login': 'LastSuccessLogin',
        'last_failed_date': 'LastFailedDate'
    }

    def __init__(self, owner_id=None, login=None, first_name=None, last_name=None, email=None, sms_phone_number=None, create_date=None, last_success_login=None, last_failed_date=None):  # noqa: E501
        """Owner - a model defined in Swagger"""  # noqa: E501
        self._owner_id = None
        self._login = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._sms_phone_number = None
        self._create_date = None
        self._last_success_login = None
        self._last_failed_date = None
        self.discriminator = None
        if owner_id is not None:
            self.owner_id = owner_id
        if login is not None:
            self.login = login
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if sms_phone_number is not None:
            self.sms_phone_number = sms_phone_number
        if create_date is not None:
            self.create_date = create_date
        if last_success_login is not None:
            self.last_success_login = last_success_login
        if last_failed_date is not None:
            self.last_failed_date = last_failed_date

    @property
    def owner_id(self):
        """Gets the owner_id of this Owner.  # noqa: E501


        :return: The owner_id of this Owner.  # noqa: E501
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this Owner.


        :param owner_id: The owner_id of this Owner.  # noqa: E501
        :type: int
        """

        self._owner_id = owner_id

    @property
    def login(self):
        """Gets the login of this Owner.  # noqa: E501


        :return: The login of this Owner.  # noqa: E501
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this Owner.


        :param login: The login of this Owner.  # noqa: E501
        :type: str
        """

        self._login = login

    @property
    def first_name(self):
        """Gets the first_name of this Owner.  # noqa: E501


        :return: The first_name of this Owner.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Owner.


        :param first_name: The first_name of this Owner.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Owner.  # noqa: E501


        :return: The last_name of this Owner.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Owner.


        :param last_name: The last_name of this Owner.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this Owner.  # noqa: E501


        :return: The email of this Owner.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Owner.


        :param email: The email of this Owner.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def sms_phone_number(self):
        """Gets the sms_phone_number of this Owner.  # noqa: E501


        :return: The sms_phone_number of this Owner.  # noqa: E501
        :rtype: str
        """
        return self._sms_phone_number

    @sms_phone_number.setter
    def sms_phone_number(self, sms_phone_number):
        """Sets the sms_phone_number of this Owner.


        :param sms_phone_number: The sms_phone_number of this Owner.  # noqa: E501
        :type: str
        """

        self._sms_phone_number = sms_phone_number

    @property
    def create_date(self):
        """Gets the create_date of this Owner.  # noqa: E501


        :return: The create_date of this Owner.  # noqa: E501
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this Owner.


        :param create_date: The create_date of this Owner.  # noqa: E501
        :type: datetime
        """

        self._create_date = create_date

    @property
    def last_success_login(self):
        """Gets the last_success_login of this Owner.  # noqa: E501


        :return: The last_success_login of this Owner.  # noqa: E501
        :rtype: datetime
        """
        return self._last_success_login

    @last_success_login.setter
    def last_success_login(self, last_success_login):
        """Sets the last_success_login of this Owner.


        :param last_success_login: The last_success_login of this Owner.  # noqa: E501
        :type: datetime
        """

        self._last_success_login = last_success_login

    @property
    def last_failed_date(self):
        """Gets the last_failed_date of this Owner.  # noqa: E501


        :return: The last_failed_date of this Owner.  # noqa: E501
        :rtype: datetime
        """
        return self._last_failed_date

    @last_failed_date.setter
    def last_failed_date(self, last_failed_date):
        """Sets the last_failed_date of this Owner.


        :param last_failed_date: The last_failed_date of this Owner.  # noqa: E501
        :type: datetime
        """

        self._last_failed_date = last_failed_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Owner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Owner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
