# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Parameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parameter_id': 'int',
        'parameter_name': 'str',
        'parameter_unit': 'str'
    }

    attribute_map = {
        'parameter_id': 'ParameterID',
        'parameter_name': 'ParameterName',
        'parameter_unit': 'ParameterUnit'
    }

    def __init__(self, parameter_id=None, parameter_name=None, parameter_unit=None):  # noqa: E501
        """Parameter - a model defined in Swagger"""  # noqa: E501
        self._parameter_id = None
        self._parameter_name = None
        self._parameter_unit = None
        self.discriminator = None
        if parameter_id is not None:
            self.parameter_id = parameter_id
        if parameter_name is not None:
            self.parameter_name = parameter_name
        if parameter_unit is not None:
            self.parameter_unit = parameter_unit

    @property
    def parameter_id(self):
        """Gets the parameter_id of this Parameter.  # noqa: E501


        :return: The parameter_id of this Parameter.  # noqa: E501
        :rtype: int
        """
        return self._parameter_id

    @parameter_id.setter
    def parameter_id(self, parameter_id):
        """Sets the parameter_id of this Parameter.


        :param parameter_id: The parameter_id of this Parameter.  # noqa: E501
        :type: int
        """

        self._parameter_id = parameter_id

    @property
    def parameter_name(self):
        """Gets the parameter_name of this Parameter.  # noqa: E501


        :return: The parameter_name of this Parameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name):
        """Sets the parameter_name of this Parameter.


        :param parameter_name: The parameter_name of this Parameter.  # noqa: E501
        :type: str
        """

        self._parameter_name = parameter_name

    @property
    def parameter_unit(self):
        """Gets the parameter_unit of this Parameter.  # noqa: E501


        :return: The parameter_unit of this Parameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_unit

    @parameter_unit.setter
    def parameter_unit(self, parameter_unit):
        """Sets the parameter_unit of this Parameter.


        :param parameter_unit: The parameter_unit of this Parameter.  # noqa: E501
        :type: str
        """

        self._parameter_unit = parameter_unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Parameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Parameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
