# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlantWeightReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plant_id': 'int',
        'plant_barcode': 'str',
        'plant_name': 'str',
        'reference_weight_value': 'float',
        'reference_weight_date': 'datetime'
    }

    attribute_map = {
        'plant_id': 'PlantID',
        'plant_barcode': 'PlantBarcode',
        'plant_name': 'PlantName',
        'reference_weight_value': 'ReferenceWeightValue',
        'reference_weight_date': 'ReferenceWeightDate'
    }

    def __init__(self, plant_id=None, plant_barcode=None, plant_name=None, reference_weight_value=None, reference_weight_date=None):  # noqa: E501
        """PlantWeightReference - a model defined in Swagger"""  # noqa: E501
        self._plant_id = None
        self._plant_barcode = None
        self._plant_name = None
        self._reference_weight_value = None
        self._reference_weight_date = None
        self.discriminator = None
        if plant_id is not None:
            self.plant_id = plant_id
        if plant_barcode is not None:
            self.plant_barcode = plant_barcode
        if plant_name is not None:
            self.plant_name = plant_name
        if reference_weight_value is not None:
            self.reference_weight_value = reference_weight_value
        if reference_weight_date is not None:
            self.reference_weight_date = reference_weight_date

    @property
    def plant_id(self):
        """Gets the plant_id of this PlantWeightReference.  # noqa: E501


        :return: The plant_id of this PlantWeightReference.  # noqa: E501
        :rtype: int
        """
        return self._plant_id

    @plant_id.setter
    def plant_id(self, plant_id):
        """Sets the plant_id of this PlantWeightReference.


        :param plant_id: The plant_id of this PlantWeightReference.  # noqa: E501
        :type: int
        """

        self._plant_id = plant_id

    @property
    def plant_barcode(self):
        """Gets the plant_barcode of this PlantWeightReference.  # noqa: E501


        :return: The plant_barcode of this PlantWeightReference.  # noqa: E501
        :rtype: str
        """
        return self._plant_barcode

    @plant_barcode.setter
    def plant_barcode(self, plant_barcode):
        """Sets the plant_barcode of this PlantWeightReference.


        :param plant_barcode: The plant_barcode of this PlantWeightReference.  # noqa: E501
        :type: str
        """

        self._plant_barcode = plant_barcode

    @property
    def plant_name(self):
        """Gets the plant_name of this PlantWeightReference.  # noqa: E501


        :return: The plant_name of this PlantWeightReference.  # noqa: E501
        :rtype: str
        """
        return self._plant_name

    @plant_name.setter
    def plant_name(self, plant_name):
        """Sets the plant_name of this PlantWeightReference.


        :param plant_name: The plant_name of this PlantWeightReference.  # noqa: E501
        :type: str
        """

        self._plant_name = plant_name

    @property
    def reference_weight_value(self):
        """Gets the reference_weight_value of this PlantWeightReference.  # noqa: E501


        :return: The reference_weight_value of this PlantWeightReference.  # noqa: E501
        :rtype: float
        """
        return self._reference_weight_value

    @reference_weight_value.setter
    def reference_weight_value(self, reference_weight_value):
        """Sets the reference_weight_value of this PlantWeightReference.


        :param reference_weight_value: The reference_weight_value of this PlantWeightReference.  # noqa: E501
        :type: float
        """

        self._reference_weight_value = reference_weight_value

    @property
    def reference_weight_date(self):
        """Gets the reference_weight_date of this PlantWeightReference.  # noqa: E501


        :return: The reference_weight_date of this PlantWeightReference.  # noqa: E501
        :rtype: datetime
        """
        return self._reference_weight_date

    @reference_weight_date.setter
    def reference_weight_date(self, reference_weight_date):
        """Sets the reference_weight_date of this PlantWeightReference.


        :param reference_weight_date: The reference_weight_date of this PlantWeightReference.  # noqa: E501
        :type: datetime
        """

        self._reference_weight_date = reference_weight_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlantWeightReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlantWeightReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
