# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProbeValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'probe_id': 'int',
        'probe_name': 'str',
        'probe_unit': 'str',
        'probe_value': 'float',
        'record_date': 'datetime'
    }

    attribute_map = {
        'probe_id': 'ProbeID',
        'probe_name': 'ProbeName',
        'probe_unit': 'ProbeUnit',
        'probe_value': 'ProbeValue',
        'record_date': 'RecordDate'
    }

    def __init__(self, probe_id=None, probe_name=None, probe_unit=None, probe_value=None, record_date=None):  # noqa: E501
        """ProbeValue - a model defined in Swagger"""  # noqa: E501
        self._probe_id = None
        self._probe_name = None
        self._probe_unit = None
        self._probe_value = None
        self._record_date = None
        self.discriminator = None
        if probe_id is not None:
            self.probe_id = probe_id
        if probe_name is not None:
            self.probe_name = probe_name
        if probe_unit is not None:
            self.probe_unit = probe_unit
        if probe_value is not None:
            self.probe_value = probe_value
        if record_date is not None:
            self.record_date = record_date

    @property
    def probe_id(self):
        """Gets the probe_id of this ProbeValue.  # noqa: E501


        :return: The probe_id of this ProbeValue.  # noqa: E501
        :rtype: int
        """
        return self._probe_id

    @probe_id.setter
    def probe_id(self, probe_id):
        """Sets the probe_id of this ProbeValue.


        :param probe_id: The probe_id of this ProbeValue.  # noqa: E501
        :type: int
        """

        self._probe_id = probe_id

    @property
    def probe_name(self):
        """Gets the probe_name of this ProbeValue.  # noqa: E501


        :return: The probe_name of this ProbeValue.  # noqa: E501
        :rtype: str
        """
        return self._probe_name

    @probe_name.setter
    def probe_name(self, probe_name):
        """Sets the probe_name of this ProbeValue.


        :param probe_name: The probe_name of this ProbeValue.  # noqa: E501
        :type: str
        """

        self._probe_name = probe_name

    @property
    def probe_unit(self):
        """Gets the probe_unit of this ProbeValue.  # noqa: E501


        :return: The probe_unit of this ProbeValue.  # noqa: E501
        :rtype: str
        """
        return self._probe_unit

    @probe_unit.setter
    def probe_unit(self, probe_unit):
        """Sets the probe_unit of this ProbeValue.


        :param probe_unit: The probe_unit of this ProbeValue.  # noqa: E501
        :type: str
        """

        self._probe_unit = probe_unit

    @property
    def probe_value(self):
        """Gets the probe_value of this ProbeValue.  # noqa: E501


        :return: The probe_value of this ProbeValue.  # noqa: E501
        :rtype: float
        """
        return self._probe_value

    @probe_value.setter
    def probe_value(self, probe_value):
        """Sets the probe_value of this ProbeValue.


        :param probe_value: The probe_value of this ProbeValue.  # noqa: E501
        :type: float
        """

        self._probe_value = probe_value

    @property
    def record_date(self):
        """Gets the record_date of this ProbeValue.  # noqa: E501


        :return: The record_date of this ProbeValue.  # noqa: E501
        :rtype: datetime
        """
        return self._record_date

    @record_date.setter
    def record_date(self, record_date):
        """Sets the record_date of this ProbeValue.


        :param record_date: The record_date of this ProbeValue.  # noqa: E501
        :type: datetime
        """

        self._record_date = record_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProbeValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProbeValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
