# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScalesData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_id': 'int',
        'device_id': 'int',
        'device_pid': 'str',
        'experiment_id': 'int',
        'measure_date': 'datetime',
        'measure_id': 'int',
        'plant_barcode': 'str',
        'plant_id': 'int',
        'plant_name': 'str',
        'plant_weight': 'float',
        'round_id': 'int',
        'tray_barcode': 'str',
        'tray_id': 'int',
        'tray_area': 'str',
        'tray_profile_id': 'int',
        'watered': 'bool'
    }

    attribute_map = {
        'action_id': 'ActionID',
        'device_id': 'DeviceID',
        'device_pid': 'DevicePID',
        'experiment_id': 'ExperimentID',
        'measure_date': 'MeasureDate',
        'measure_id': 'MeasureID',
        'plant_barcode': 'PlantBarcode',
        'plant_id': 'PlantID',
        'plant_name': 'PlantName',
        'plant_weight': 'PlantWeight',
        'round_id': 'RoundID',
        'tray_barcode': 'TrayBarcode',
        'tray_id': 'TrayID',
        'tray_area': 'TrayArea',
        'tray_profile_id': 'TrayProfileID',
        'watered': 'Watered'
    }

    def __init__(self, action_id=None, device_id=None, device_pid=None, experiment_id=None, measure_date=None, measure_id=None, plant_barcode=None, plant_id=None, plant_name=None, plant_weight=None, round_id=None, tray_barcode=None, tray_id=None, tray_area=None, tray_profile_id=None, watered=None):  # noqa: E501
        """ScalesData - a model defined in Swagger"""  # noqa: E501
        self._action_id = None
        self._device_id = None
        self._device_pid = None
        self._experiment_id = None
        self._measure_date = None
        self._measure_id = None
        self._plant_barcode = None
        self._plant_id = None
        self._plant_name = None
        self._plant_weight = None
        self._round_id = None
        self._tray_barcode = None
        self._tray_id = None
        self._tray_area = None
        self._tray_profile_id = None
        self._watered = None
        self.discriminator = None
        if action_id is not None:
            self.action_id = action_id
        if device_id is not None:
            self.device_id = device_id
        if device_pid is not None:
            self.device_pid = device_pid
        if experiment_id is not None:
            self.experiment_id = experiment_id
        if measure_date is not None:
            self.measure_date = measure_date
        if measure_id is not None:
            self.measure_id = measure_id
        if plant_barcode is not None:
            self.plant_barcode = plant_barcode
        if plant_id is not None:
            self.plant_id = plant_id
        if plant_name is not None:
            self.plant_name = plant_name
        if plant_weight is not None:
            self.plant_weight = plant_weight
        if round_id is not None:
            self.round_id = round_id
        if tray_barcode is not None:
            self.tray_barcode = tray_barcode
        if tray_id is not None:
            self.tray_id = tray_id
        if tray_area is not None:
            self.tray_area = tray_area
        if tray_profile_id is not None:
            self.tray_profile_id = tray_profile_id
        if watered is not None:
            self.watered = watered

    @property
    def action_id(self):
        """Gets the action_id of this ScalesData.  # noqa: E501


        :return: The action_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this ScalesData.


        :param action_id: The action_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._action_id = action_id

    @property
    def device_id(self):
        """Gets the device_id of this ScalesData.  # noqa: E501


        :return: The device_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this ScalesData.


        :param device_id: The device_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def device_pid(self):
        """Gets the device_pid of this ScalesData.  # noqa: E501


        :return: The device_pid of this ScalesData.  # noqa: E501
        :rtype: str
        """
        return self._device_pid

    @device_pid.setter
    def device_pid(self, device_pid):
        """Sets the device_pid of this ScalesData.


        :param device_pid: The device_pid of this ScalesData.  # noqa: E501
        :type: str
        """

        self._device_pid = device_pid

    @property
    def experiment_id(self):
        """Gets the experiment_id of this ScalesData.  # noqa: E501


        :return: The experiment_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._experiment_id

    @experiment_id.setter
    def experiment_id(self, experiment_id):
        """Sets the experiment_id of this ScalesData.


        :param experiment_id: The experiment_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._experiment_id = experiment_id

    @property
    def measure_date(self):
        """Gets the measure_date of this ScalesData.  # noqa: E501


        :return: The measure_date of this ScalesData.  # noqa: E501
        :rtype: datetime
        """
        return self._measure_date

    @measure_date.setter
    def measure_date(self, measure_date):
        """Sets the measure_date of this ScalesData.


        :param measure_date: The measure_date of this ScalesData.  # noqa: E501
        :type: datetime
        """

        self._measure_date = measure_date

    @property
    def measure_id(self):
        """Gets the measure_id of this ScalesData.  # noqa: E501


        :return: The measure_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._measure_id

    @measure_id.setter
    def measure_id(self, measure_id):
        """Sets the measure_id of this ScalesData.


        :param measure_id: The measure_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._measure_id = measure_id

    @property
    def plant_barcode(self):
        """Gets the plant_barcode of this ScalesData.  # noqa: E501


        :return: The plant_barcode of this ScalesData.  # noqa: E501
        :rtype: str
        """
        return self._plant_barcode

    @plant_barcode.setter
    def plant_barcode(self, plant_barcode):
        """Sets the plant_barcode of this ScalesData.


        :param plant_barcode: The plant_barcode of this ScalesData.  # noqa: E501
        :type: str
        """

        self._plant_barcode = plant_barcode

    @property
    def plant_id(self):
        """Gets the plant_id of this ScalesData.  # noqa: E501


        :return: The plant_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._plant_id

    @plant_id.setter
    def plant_id(self, plant_id):
        """Sets the plant_id of this ScalesData.


        :param plant_id: The plant_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._plant_id = plant_id

    @property
    def plant_name(self):
        """Gets the plant_name of this ScalesData.  # noqa: E501


        :return: The plant_name of this ScalesData.  # noqa: E501
        :rtype: str
        """
        return self._plant_name

    @plant_name.setter
    def plant_name(self, plant_name):
        """Sets the plant_name of this ScalesData.


        :param plant_name: The plant_name of this ScalesData.  # noqa: E501
        :type: str
        """

        self._plant_name = plant_name

    @property
    def plant_weight(self):
        """Gets the plant_weight of this ScalesData.  # noqa: E501


        :return: The plant_weight of this ScalesData.  # noqa: E501
        :rtype: float
        """
        return self._plant_weight

    @plant_weight.setter
    def plant_weight(self, plant_weight):
        """Sets the plant_weight of this ScalesData.


        :param plant_weight: The plant_weight of this ScalesData.  # noqa: E501
        :type: float
        """

        self._plant_weight = plant_weight

    @property
    def round_id(self):
        """Gets the round_id of this ScalesData.  # noqa: E501


        :return: The round_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._round_id

    @round_id.setter
    def round_id(self, round_id):
        """Sets the round_id of this ScalesData.


        :param round_id: The round_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._round_id = round_id

    @property
    def tray_barcode(self):
        """Gets the tray_barcode of this ScalesData.  # noqa: E501


        :return: The tray_barcode of this ScalesData.  # noqa: E501
        :rtype: str
        """
        return self._tray_barcode

    @tray_barcode.setter
    def tray_barcode(self, tray_barcode):
        """Sets the tray_barcode of this ScalesData.


        :param tray_barcode: The tray_barcode of this ScalesData.  # noqa: E501
        :type: str
        """

        self._tray_barcode = tray_barcode

    @property
    def tray_id(self):
        """Gets the tray_id of this ScalesData.  # noqa: E501


        :return: The tray_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._tray_id

    @tray_id.setter
    def tray_id(self, tray_id):
        """Sets the tray_id of this ScalesData.


        :param tray_id: The tray_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._tray_id = tray_id

    @property
    def tray_area(self):
        """Gets the tray_area of this ScalesData.  # noqa: E501


        :return: The tray_area of this ScalesData.  # noqa: E501
        :rtype: str
        """
        return self._tray_area

    @tray_area.setter
    def tray_area(self, tray_area):
        """Sets the tray_area of this ScalesData.


        :param tray_area: The tray_area of this ScalesData.  # noqa: E501
        :type: str
        """

        self._tray_area = tray_area

    @property
    def tray_profile_id(self):
        """Gets the tray_profile_id of this ScalesData.  # noqa: E501


        :return: The tray_profile_id of this ScalesData.  # noqa: E501
        :rtype: int
        """
        return self._tray_profile_id

    @tray_profile_id.setter
    def tray_profile_id(self, tray_profile_id):
        """Sets the tray_profile_id of this ScalesData.


        :param tray_profile_id: The tray_profile_id of this ScalesData.  # noqa: E501
        :type: int
        """

        self._tray_profile_id = tray_profile_id

    @property
    def watered(self):
        """Gets the watered of this ScalesData.  # noqa: E501


        :return: The watered of this ScalesData.  # noqa: E501
        :rtype: bool
        """
        return self._watered

    @watered.setter
    def watered(self, watered):
        """Sets the watered of this ScalesData.


        :param watered: The watered of this ScalesData.  # noqa: E501
        :type: bool
        """

        self._watered = watered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScalesData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScalesData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
