# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SprayAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_id': 'int',
        'device_pid': 'str',
        'experiment_id': 'int',
        'action_id': 'int',
        'round_id': 'int',
        'tray_profile_id': 'int',
        'tray_id': 'int',
        'tray_barcode': 'str',
        'tray_area': 'str',
        'plant_id': 'int',
        'plant_barcode': 'str',
        'plant_name': 'str',
        'spray_action_id': 'int',
        'spray_action_date': 'datetime',
        'spray_time': 'int',
        'liquid_amount': 'int',
        'liquid_name': 'str'
    }

    attribute_map = {
        'device_id': 'DeviceID',
        'device_pid': 'DevicePID',
        'experiment_id': 'ExperimentID',
        'action_id': 'ActionID',
        'round_id': 'RoundID',
        'tray_profile_id': 'TrayProfileID',
        'tray_id': 'TrayID',
        'tray_barcode': 'TrayBarcode',
        'tray_area': 'TrayArea',
        'plant_id': 'PlantID',
        'plant_barcode': 'PlantBarcode',
        'plant_name': 'PlantName',
        'spray_action_id': 'SprayActionID',
        'spray_action_date': 'SprayActionDate',
        'spray_time': 'SprayTime',
        'liquid_amount': 'LiquidAmount',
        'liquid_name': 'LiquidName'
    }

    def __init__(self, device_id=None, device_pid=None, experiment_id=None, action_id=None, round_id=None, tray_profile_id=None, tray_id=None, tray_barcode=None, tray_area=None, plant_id=None, plant_barcode=None, plant_name=None, spray_action_id=None, spray_action_date=None, spray_time=None, liquid_amount=None, liquid_name=None):  # noqa: E501
        """SprayAction - a model defined in Swagger"""  # noqa: E501
        self._device_id = None
        self._device_pid = None
        self._experiment_id = None
        self._action_id = None
        self._round_id = None
        self._tray_profile_id = None
        self._tray_id = None
        self._tray_barcode = None
        self._tray_area = None
        self._plant_id = None
        self._plant_barcode = None
        self._plant_name = None
        self._spray_action_id = None
        self._spray_action_date = None
        self._spray_time = None
        self._liquid_amount = None
        self._liquid_name = None
        self.discriminator = None
        if device_id is not None:
            self.device_id = device_id
        if device_pid is not None:
            self.device_pid = device_pid
        if experiment_id is not None:
            self.experiment_id = experiment_id
        if action_id is not None:
            self.action_id = action_id
        if round_id is not None:
            self.round_id = round_id
        if tray_profile_id is not None:
            self.tray_profile_id = tray_profile_id
        if tray_id is not None:
            self.tray_id = tray_id
        if tray_barcode is not None:
            self.tray_barcode = tray_barcode
        if tray_area is not None:
            self.tray_area = tray_area
        if plant_id is not None:
            self.plant_id = plant_id
        if plant_barcode is not None:
            self.plant_barcode = plant_barcode
        if plant_name is not None:
            self.plant_name = plant_name
        if spray_action_id is not None:
            self.spray_action_id = spray_action_id
        if spray_action_date is not None:
            self.spray_action_date = spray_action_date
        if spray_time is not None:
            self.spray_time = spray_time
        if liquid_amount is not None:
            self.liquid_amount = liquid_amount
        if liquid_name is not None:
            self.liquid_name = liquid_name

    @property
    def device_id(self):
        """Gets the device_id of this SprayAction.  # noqa: E501


        :return: The device_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this SprayAction.


        :param device_id: The device_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def device_pid(self):
        """Gets the device_pid of this SprayAction.  # noqa: E501


        :return: The device_pid of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._device_pid

    @device_pid.setter
    def device_pid(self, device_pid):
        """Sets the device_pid of this SprayAction.


        :param device_pid: The device_pid of this SprayAction.  # noqa: E501
        :type: str
        """

        self._device_pid = device_pid

    @property
    def experiment_id(self):
        """Gets the experiment_id of this SprayAction.  # noqa: E501


        :return: The experiment_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._experiment_id

    @experiment_id.setter
    def experiment_id(self, experiment_id):
        """Sets the experiment_id of this SprayAction.


        :param experiment_id: The experiment_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._experiment_id = experiment_id

    @property
    def action_id(self):
        """Gets the action_id of this SprayAction.  # noqa: E501


        :return: The action_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this SprayAction.


        :param action_id: The action_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._action_id = action_id

    @property
    def round_id(self):
        """Gets the round_id of this SprayAction.  # noqa: E501


        :return: The round_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._round_id

    @round_id.setter
    def round_id(self, round_id):
        """Sets the round_id of this SprayAction.


        :param round_id: The round_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._round_id = round_id

    @property
    def tray_profile_id(self):
        """Gets the tray_profile_id of this SprayAction.  # noqa: E501


        :return: The tray_profile_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._tray_profile_id

    @tray_profile_id.setter
    def tray_profile_id(self, tray_profile_id):
        """Sets the tray_profile_id of this SprayAction.


        :param tray_profile_id: The tray_profile_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._tray_profile_id = tray_profile_id

    @property
    def tray_id(self):
        """Gets the tray_id of this SprayAction.  # noqa: E501


        :return: The tray_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._tray_id

    @tray_id.setter
    def tray_id(self, tray_id):
        """Sets the tray_id of this SprayAction.


        :param tray_id: The tray_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._tray_id = tray_id

    @property
    def tray_barcode(self):
        """Gets the tray_barcode of this SprayAction.  # noqa: E501


        :return: The tray_barcode of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._tray_barcode

    @tray_barcode.setter
    def tray_barcode(self, tray_barcode):
        """Sets the tray_barcode of this SprayAction.


        :param tray_barcode: The tray_barcode of this SprayAction.  # noqa: E501
        :type: str
        """

        self._tray_barcode = tray_barcode

    @property
    def tray_area(self):
        """Gets the tray_area of this SprayAction.  # noqa: E501


        :return: The tray_area of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._tray_area

    @tray_area.setter
    def tray_area(self, tray_area):
        """Sets the tray_area of this SprayAction.


        :param tray_area: The tray_area of this SprayAction.  # noqa: E501
        :type: str
        """

        self._tray_area = tray_area

    @property
    def plant_id(self):
        """Gets the plant_id of this SprayAction.  # noqa: E501


        :return: The plant_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._plant_id

    @plant_id.setter
    def plant_id(self, plant_id):
        """Sets the plant_id of this SprayAction.


        :param plant_id: The plant_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._plant_id = plant_id

    @property
    def plant_barcode(self):
        """Gets the plant_barcode of this SprayAction.  # noqa: E501


        :return: The plant_barcode of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._plant_barcode

    @plant_barcode.setter
    def plant_barcode(self, plant_barcode):
        """Sets the plant_barcode of this SprayAction.


        :param plant_barcode: The plant_barcode of this SprayAction.  # noqa: E501
        :type: str
        """

        self._plant_barcode = plant_barcode

    @property
    def plant_name(self):
        """Gets the plant_name of this SprayAction.  # noqa: E501


        :return: The plant_name of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._plant_name

    @plant_name.setter
    def plant_name(self, plant_name):
        """Sets the plant_name of this SprayAction.


        :param plant_name: The plant_name of this SprayAction.  # noqa: E501
        :type: str
        """

        self._plant_name = plant_name

    @property
    def spray_action_id(self):
        """Gets the spray_action_id of this SprayAction.  # noqa: E501


        :return: The spray_action_id of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._spray_action_id

    @spray_action_id.setter
    def spray_action_id(self, spray_action_id):
        """Sets the spray_action_id of this SprayAction.


        :param spray_action_id: The spray_action_id of this SprayAction.  # noqa: E501
        :type: int
        """

        self._spray_action_id = spray_action_id

    @property
    def spray_action_date(self):
        """Gets the spray_action_date of this SprayAction.  # noqa: E501


        :return: The spray_action_date of this SprayAction.  # noqa: E501
        :rtype: datetime
        """
        return self._spray_action_date

    @spray_action_date.setter
    def spray_action_date(self, spray_action_date):
        """Sets the spray_action_date of this SprayAction.


        :param spray_action_date: The spray_action_date of this SprayAction.  # noqa: E501
        :type: datetime
        """

        self._spray_action_date = spray_action_date

    @property
    def spray_time(self):
        """Gets the spray_time of this SprayAction.  # noqa: E501


        :return: The spray_time of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._spray_time

    @spray_time.setter
    def spray_time(self, spray_time):
        """Sets the spray_time of this SprayAction.


        :param spray_time: The spray_time of this SprayAction.  # noqa: E501
        :type: int
        """

        self._spray_time = spray_time

    @property
    def liquid_amount(self):
        """Gets the liquid_amount of this SprayAction.  # noqa: E501


        :return: The liquid_amount of this SprayAction.  # noqa: E501
        :rtype: int
        """
        return self._liquid_amount

    @liquid_amount.setter
    def liquid_amount(self, liquid_amount):
        """Sets the liquid_amount of this SprayAction.


        :param liquid_amount: The liquid_amount of this SprayAction.  # noqa: E501
        :type: int
        """

        self._liquid_amount = liquid_amount

    @property
    def liquid_name(self):
        """Gets the liquid_name of this SprayAction.  # noqa: E501


        :return: The liquid_name of this SprayAction.  # noqa: E501
        :rtype: str
        """
        return self._liquid_name

    @liquid_name.setter
    def liquid_name(self, liquid_name):
        """Sets the liquid_name of this SprayAction.


        :param liquid_name: The liquid_name of this SprayAction.  # noqa: E501
        :type: str
        """

        self._liquid_name = liquid_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SprayAction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SprayAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
