# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'profile_active': 'bool',
        'profile_id': 'int',
        'profile_info': 'str',
        'profile_name': 'str',
        'system_hw_config': 'str'
    }

    attribute_map = {
        'profile_active': 'ProfileActive',
        'profile_id': 'ProfileID',
        'profile_info': 'ProfileInfo',
        'profile_name': 'ProfileName',
        'system_hw_config': 'SystemHwConfig'
    }

    def __init__(self, profile_active=None, profile_id=None, profile_info=None, profile_name=None, system_hw_config=None):  # noqa: E501
        """SystemProfile - a model defined in Swagger"""  # noqa: E501
        self._profile_active = None
        self._profile_id = None
        self._profile_info = None
        self._profile_name = None
        self._system_hw_config = None
        self.discriminator = None
        if profile_active is not None:
            self.profile_active = profile_active
        if profile_id is not None:
            self.profile_id = profile_id
        if profile_info is not None:
            self.profile_info = profile_info
        if profile_name is not None:
            self.profile_name = profile_name
        if system_hw_config is not None:
            self.system_hw_config = system_hw_config

    @property
    def profile_active(self):
        """Gets the profile_active of this SystemProfile.  # noqa: E501


        :return: The profile_active of this SystemProfile.  # noqa: E501
        :rtype: bool
        """
        return self._profile_active

    @profile_active.setter
    def profile_active(self, profile_active):
        """Sets the profile_active of this SystemProfile.


        :param profile_active: The profile_active of this SystemProfile.  # noqa: E501
        :type: bool
        """

        self._profile_active = profile_active

    @property
    def profile_id(self):
        """Gets the profile_id of this SystemProfile.  # noqa: E501


        :return: The profile_id of this SystemProfile.  # noqa: E501
        :rtype: int
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id):
        """Sets the profile_id of this SystemProfile.


        :param profile_id: The profile_id of this SystemProfile.  # noqa: E501
        :type: int
        """

        self._profile_id = profile_id

    @property
    def profile_info(self):
        """Gets the profile_info of this SystemProfile.  # noqa: E501


        :return: The profile_info of this SystemProfile.  # noqa: E501
        :rtype: str
        """
        return self._profile_info

    @profile_info.setter
    def profile_info(self, profile_info):
        """Sets the profile_info of this SystemProfile.


        :param profile_info: The profile_info of this SystemProfile.  # noqa: E501
        :type: str
        """

        self._profile_info = profile_info

    @property
    def profile_name(self):
        """Gets the profile_name of this SystemProfile.  # noqa: E501


        :return: The profile_name of this SystemProfile.  # noqa: E501
        :rtype: str
        """
        return self._profile_name

    @profile_name.setter
    def profile_name(self, profile_name):
        """Sets the profile_name of this SystemProfile.


        :param profile_name: The profile_name of this SystemProfile.  # noqa: E501
        :type: str
        """

        self._profile_name = profile_name

    @property
    def system_hw_config(self):
        """Gets the system_hw_config of this SystemProfile.  # noqa: E501


        :return: The system_hw_config of this SystemProfile.  # noqa: E501
        :rtype: str
        """
        return self._system_hw_config

    @system_hw_config.setter
    def system_hw_config(self, system_hw_config):
        """Sets the system_hw_config of this SystemProfile.


        :param system_hw_config: The system_hw_config of this SystemProfile.  # noqa: E501
        :type: str
        """

        self._system_hw_config = system_hw_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
