# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TrayProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'profile_id': 'int',
        'tray_id': 'int',
        'profile_name': 'str',
        'profile_date_start': 'datetime',
        'profile_date_stop': 'datetime'
    }

    attribute_map = {
        'profile_id': 'ProfileID',
        'tray_id': 'TrayID',
        'profile_name': 'ProfileName',
        'profile_date_start': 'ProfileDateStart',
        'profile_date_stop': 'ProfileDateStop'
    }

    def __init__(self, profile_id=None, tray_id=None, profile_name=None, profile_date_start=None, profile_date_stop=None):  # noqa: E501
        """TrayProfile - a model defined in Swagger"""  # noqa: E501
        self._profile_id = None
        self._tray_id = None
        self._profile_name = None
        self._profile_date_start = None
        self._profile_date_stop = None
        self.discriminator = None
        if profile_id is not None:
            self.profile_id = profile_id
        if tray_id is not None:
            self.tray_id = tray_id
        if profile_name is not None:
            self.profile_name = profile_name
        if profile_date_start is not None:
            self.profile_date_start = profile_date_start
        if profile_date_stop is not None:
            self.profile_date_stop = profile_date_stop

    @property
    def profile_id(self):
        """Gets the profile_id of this TrayProfile.  # noqa: E501


        :return: The profile_id of this TrayProfile.  # noqa: E501
        :rtype: int
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id):
        """Sets the profile_id of this TrayProfile.


        :param profile_id: The profile_id of this TrayProfile.  # noqa: E501
        :type: int
        """

        self._profile_id = profile_id

    @property
    def tray_id(self):
        """Gets the tray_id of this TrayProfile.  # noqa: E501


        :return: The tray_id of this TrayProfile.  # noqa: E501
        :rtype: int
        """
        return self._tray_id

    @tray_id.setter
    def tray_id(self, tray_id):
        """Sets the tray_id of this TrayProfile.


        :param tray_id: The tray_id of this TrayProfile.  # noqa: E501
        :type: int
        """

        self._tray_id = tray_id

    @property
    def profile_name(self):
        """Gets the profile_name of this TrayProfile.  # noqa: E501


        :return: The profile_name of this TrayProfile.  # noqa: E501
        :rtype: str
        """
        return self._profile_name

    @profile_name.setter
    def profile_name(self, profile_name):
        """Sets the profile_name of this TrayProfile.


        :param profile_name: The profile_name of this TrayProfile.  # noqa: E501
        :type: str
        """

        self._profile_name = profile_name

    @property
    def profile_date_start(self):
        """Gets the profile_date_start of this TrayProfile.  # noqa: E501


        :return: The profile_date_start of this TrayProfile.  # noqa: E501
        :rtype: datetime
        """
        return self._profile_date_start

    @profile_date_start.setter
    def profile_date_start(self, profile_date_start):
        """Sets the profile_date_start of this TrayProfile.


        :param profile_date_start: The profile_date_start of this TrayProfile.  # noqa: E501
        :type: datetime
        """

        self._profile_date_start = profile_date_start

    @property
    def profile_date_stop(self):
        """Gets the profile_date_stop of this TrayProfile.  # noqa: E501


        :return: The profile_date_stop of this TrayProfile.  # noqa: E501
        :rtype: datetime
        """
        return self._profile_date_stop

    @profile_date_stop.setter
    def profile_date_stop(self, profile_date_stop):
        """Sets the profile_date_stop of this TrayProfile.


        :param profile_date_stop: The profile_date_stop of this TrayProfile.  # noqa: E501
        :type: datetime
        """

        self._profile_date_stop = profile_date_stop

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrayProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrayProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
