# coding: utf-8

"""
    PSI Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from plantscreen.swagger_client.api_client import ApiClient


class IrApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def ir_imaging(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrImagingResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_imaging_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_imaging_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
            return data

    def ir_imaging_with_http_info(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_with_http_info(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrImagingResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_imaging" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_imaging`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_imaging`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_imaging`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Imaging', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrImagingResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_imaging_extended_data(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal extended data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID. (Only available for field systems.)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_extended_data(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrMeasureExtendedDataResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_imaging_extended_data_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_imaging_extended_data_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
            return data

    def ir_imaging_extended_data_with_http_info(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal extended data for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID. (Only available for field systems.)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_extended_data_with_http_info(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrMeasureExtendedDataResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_imaging_extended_data" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_imaging_extended_data`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_imaging_extended_data`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_imaging_extended_data`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Imaging/ExtendedData', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrMeasureExtendedDataResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_imaging_extended_data_measure(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging extended data by IR measure ID. (Only available for field systems.)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_extended_data_measure(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrMeasureExtendedDataByIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_imaging_extended_data_measure_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_imaging_extended_data_measure_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_imaging_extended_data_measure_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging extended data by IR measure ID. (Only available for field systems.)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_extended_data_measure_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrMeasureExtendedDataByIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_imaging_extended_data_measure" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_imaging_extended_data_measure`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Imaging/ExtendedData/Measure', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrMeasureExtendedDataByIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_imaging_measure(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_measure(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrImagingByIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_imaging_measure_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_imaging_measure_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_imaging_measure_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_imaging_measure_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrImagingByIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_imaging_measure" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_imaging_measure`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Imaging/Measure', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrImagingByIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_leaf_param(self, device_id, round_id, tray_id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal Statistic leaf parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_leaf_param(device_id, round_id, tray_id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :param int param_id: paramID (required)
        :return: JsonIrLeafParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_leaf_param_with_http_info(device_id, round_id, tray_id, param_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_leaf_param_with_http_info(device_id, round_id, tray_id, param_id, **kwargs)  # noqa: E501
            return data

    def ir_leaf_param_with_http_info(self, device_id, round_id, tray_id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal Statistic leaf parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_leaf_param_with_http_info(device_id, round_id, tray_id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :param int param_id: paramID (required)
        :return: JsonIrLeafParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id', 'param_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_leaf_param" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_leaf_param`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_leaf_param`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_leaf_param`")  # noqa: E501
        # verify the required parameter 'param_id' is set
        if ('param_id' not in params or
                params['param_id'] is None):
            raise ValueError("Missing the required parameter `param_id` when calling `ir_leaf_param`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501
        if 'param_id' in params:
            query_params.append(('paramId', params['param_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Leaf/Param', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrLeafParamResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_leaf_param_analyse(self, id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal statistic leaf parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_leaf_param_analyse(id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :param int param_id: paramID (required)
        :return: JsonIrLeafParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_leaf_param_analyse_with_http_info(id, param_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_leaf_param_analyse_with_http_info(id, param_id, **kwargs)  # noqa: E501
            return data

    def ir_leaf_param_analyse_with_http_info(self, id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal statistic leaf parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_leaf_param_analyse_with_http_info(id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :param int param_id: paramID (required)
        :return: JsonIrLeafParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'param_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_leaf_param_analyse" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_leaf_param_analyse`")  # noqa: E501
        # verify the required parameter 'param_id' is set
        if ('param_id' not in params or
                params['param_id'] is None):
            raise ValueError("Missing the required parameter `param_id` when calling `ir_leaf_param_analyse`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'param_id' in params:
            query_params.append(('paramId', params['param_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Leaf/Param/Analyse', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrLeafParamByAnalyseIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_param(self, id, **kwargs):  # noqa: E501
        """Returns one Thermal parameter by parameter ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: paramID (required)
        :return: JsonIrParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_param_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_param_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_param_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns one Thermal parameter by parameter ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: paramID (required)
        :return: JsonIrParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_param" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_param`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Param', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrParamResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_param_used(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns the Thermal plant and leaf parameters used in the analysis by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param_used(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrUsedParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_param_used_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_param_used_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
            return data

    def ir_param_used_with_http_info(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns the Thermal plant and leaf parameters used in the analysis by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param_used_with_http_info(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrUsedParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_param_used" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_param_used`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_param_used`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_param_used`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Param/Used', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrUsedParamResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_param_used_analyse(self, id, **kwargs):  # noqa: E501
        """Returns the Thermalplant and leaf parameters used in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param_used_analyse(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :return: JsonIrUsedParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_param_used_analyse_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_param_used_analyse_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_param_used_analyse_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns the Thermalplant and leaf parameters used in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_param_used_analyse_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :return: JsonIrUsedParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_param_used_analyse" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_param_used_analyse`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Param/Used/Analyse', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrUsedParamByAnalyseIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_mask(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal plant masks created for the tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrPlantMaskResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_mask_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_mask_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
            return data

    def ir_plant_mask_with_http_info(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal plant masks created for the tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_with_http_info(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrPlantMaskResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_mask" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_plant_mask`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_plant_mask`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_plant_mask`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Mask', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantMaskResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_mask_image(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data masked by the plant mask for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_image(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrPlantMaskImageResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_mask_image_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_mask_image_with_http_info(device_id, round_id, tray_id, **kwargs)  # noqa: E501
            return data

    def ir_plant_mask_image_with_http_info(self, device_id, round_id, tray_id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data masked by the plant mask for tray defined by tray ID, by round ID of round in which the tray was measured and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_image_with_http_info(device_id, round_id, tray_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :return: JsonIrPlantMaskImageResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_mask_image" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_plant_mask_image`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_plant_mask_image`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_plant_mask_image`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Mask/Image', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantMaskImageResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_mask_image_measure(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data masked by the plant mask defined by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_image_measure(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrPlantMaskImageByMeasureIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_mask_image_measure_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_mask_image_measure_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_plant_mask_image_measure_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns Thermal imaging data masked by the plant mask defined by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_image_measure_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrPlantMaskImageByMeasureIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_mask_image_measure" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_plant_mask_image_measure`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Mask/Image/Measure', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantMaskImageByMeasureIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_mask_measure(self, id, **kwargs):  # noqa: E501
        """Returns the Thermal plant mask created for the measured tray defined by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_measure(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrPlantMaskByMeasureIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_mask_measure_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_mask_measure_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def ir_plant_mask_measure_with_http_info(self, id, **kwargs):  # noqa: E501
        """Returns the Thermal plant mask created for the measured tray defined by IR measure ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_mask_measure_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: measureID (required)
        :return: JsonIrPlantMaskByMeasureIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_mask_measure" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_plant_mask_measure`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Mask/Measure', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantMaskByMeasureIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_param(self, device_id, round_id, tray_id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal statistic plant parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_param(device_id, round_id, tray_id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :param int param_id: paramID (required)
        :return: JsonIrPlantParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_param_with_http_info(device_id, round_id, tray_id, param_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_param_with_http_info(device_id, round_id, tray_id, param_id, **kwargs)  # noqa: E501
            return data

    def ir_plant_param_with_http_info(self, device_id, round_id, tray_id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal statistic plant parameter values for the parameter defined by parameter ID, by tray ID, by round ID of round in which the tray was analyzed and by device defined by device ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_param_with_http_info(device_id, round_id, tray_id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int device_id: deviceID (required)
        :param int round_id: roundID (required)
        :param int tray_id: trayID (required)
        :param int param_id: paramID (required)
        :return: JsonIrPlantParamResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_id', 'round_id', 'tray_id', 'param_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_param" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_id' is set
        if ('device_id' not in params or
                params['device_id'] is None):
            raise ValueError("Missing the required parameter `device_id` when calling `ir_plant_param`")  # noqa: E501
        # verify the required parameter 'round_id' is set
        if ('round_id' not in params or
                params['round_id'] is None):
            raise ValueError("Missing the required parameter `round_id` when calling `ir_plant_param`")  # noqa: E501
        # verify the required parameter 'tray_id' is set
        if ('tray_id' not in params or
                params['tray_id'] is None):
            raise ValueError("Missing the required parameter `tray_id` when calling `ir_plant_param`")  # noqa: E501
        # verify the required parameter 'param_id' is set
        if ('param_id' not in params or
                params['param_id'] is None):
            raise ValueError("Missing the required parameter `param_id` when calling `ir_plant_param`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'device_id' in params:
            query_params.append(('deviceId', params['device_id']))  # noqa: E501
        if 'round_id' in params:
            query_params.append(('roundId', params['round_id']))  # noqa: E501
        if 'tray_id' in params:
            query_params.append(('trayId', params['tray_id']))  # noqa: E501
        if 'param_id' in params:
            query_params.append(('paramId', params['param_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Param', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantParamResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ir_plant_param_analyse(self, id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal plant parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_param_analyse(id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :param int param_id: ParamID (required)
        :return: JsonIrPlantParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ir_plant_param_analyse_with_http_info(id, param_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ir_plant_param_analyse_with_http_info(id, param_id, **kwargs)  # noqa: E501
            return data

    def ir_plant_param_analyse_with_http_info(self, id, param_id, **kwargs):  # noqa: E501
        """Returns the Thermal plant parameter values for the parameter defined by parameter ID and calculated in the analysis defined by analyse ID.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ir_plant_param_analyse_with_http_info(id, param_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: analyseID (required)
        :param int param_id: ParamID (required)
        :return: JsonIrPlantParamByAnalyseIDResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'param_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ir_plant_param_analyse" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `ir_plant_param_analyse`")  # noqa: E501
        # verify the required parameter 'param_id' is set
        if ('param_id' not in params or
                params['param_id'] is None):
            raise ValueError("Missing the required parameter `param_id` when calling `ir_plant_param_analyse`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'param_id' in params:
            query_params.append(('paramId', params['param_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Ir/Plant/Param/Analyse', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JsonIrPlantParamByAnalyseIDResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
