name: Build and Deploy Documentation

on:
  workflow_run:
    workflows: ["Generate Python Client from OpenAPI Spec"]
    types:
      - completed

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main branch
        if: github.event.workflow_run.head_branch != 'main'
        run: echo "Not on main branch, skipping." && exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Copy int.md to docs/
        run: |
          cp docs/int.md docs/docs/int.md

      - name: Copy README.md to docs/
        run: |
          cp README.md docs/README.md

      - name: Install dependencies
        run: |
          pip install .[build]

      - name: Run update_docs.py
        run: python post_generation/update_docs.py

      - name: Build documentation
        run: |
          mkdocs build

      - name: Commit and push generated client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Using GITHUB_TOKEN for authentication"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m 'chore: update docs' || echo 'No changes to commit'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
