name: Build and Deploy Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Python Client from OpenAPI Spec"]
    types: [completed]
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main branch
        if: github.event.workflow_run.head_branch != 'main'
        run: echo "Not on main branch, skipping." && exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install .[build]

      - name: Build documentation
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
